; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5

; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1030 -mattr=-unaligned-access-mode %s -o - | FileCheck %s

; For checking that LowerMemIntrinsics lowers memcpy and memmove with large
; constant copy-sizes into loops with multiple load/store pairs.

define void @memmove_p1_p1_sz2048(ptr addrspace(1) align 1 %dst, ptr addrspace(1) align 1 readonly %src) #1 {
;
; CHECK-LABEL: memmove_p1_p1_sz2048:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v57, off, s[0:3], s32 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b32 s4, exec_lo
; CHECK-NEXT:    v_cmpx_ge_u64_e32 v[2:3], v[0:1]
; CHECK-NEXT:    s_xor_b32 s6, exec_lo, s4
; CHECK-NEXT:    s_cbranch_execz .LBB0_3
; CHECK-NEXT:  ; %bb.1: ; %memmove_fwd_loop.preheader
; CHECK-NEXT:    s_mov_b64 s[4:5], 0x800
; CHECK-NEXT:  .LBB0_2: ; %memmove_fwd_loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_clause 0xf
; CHECK-NEXT:    global_load_dwordx4 v[16:19], v[2:3], off offset:240
; CHECK-NEXT:    global_load_dwordx4 v[20:23], v[2:3], off offset:224
; CHECK-NEXT:    global_load_dwordx4 v[4:7], v[2:3], off
; CHECK-NEXT:    global_load_dwordx4 v[8:11], v[2:3], off offset:16
; CHECK-NEXT:    global_load_dwordx4 v[12:15], v[2:3], off offset:32
; CHECK-NEXT:    global_load_dwordx4 v[96:99], v[2:3], off offset:48
; CHECK-NEXT:    global_load_dwordx4 v[84:87], v[2:3], off offset:64
; CHECK-NEXT:    global_load_dwordx4 v[80:83], v[2:3], off offset:80
; CHECK-NEXT:    global_load_dwordx4 v[68:71], v[2:3], off offset:96
; CHECK-NEXT:    global_load_dwordx4 v[64:67], v[2:3], off offset:112
; CHECK-NEXT:    global_load_dwordx4 v[52:55], v[2:3], off offset:128
; CHECK-NEXT:    global_load_dwordx4 v[48:51], v[2:3], off offset:144
; CHECK-NEXT:    global_load_dwordx4 v[36:39], v[2:3], off offset:160
; CHECK-NEXT:    global_load_dwordx4 v[32:35], v[2:3], off offset:176
; CHECK-NEXT:    global_load_dwordx4 v[28:31], v[2:3], off offset:192
; CHECK-NEXT:    global_load_dwordx4 v[24:27], v[2:3], off offset:208
; CHECK-NEXT:    v_add_co_u32 v2, vcc_lo, 0x100, v2
; CHECK-NEXT:    v_add_co_ci_u32_e64 v3, null, 0, v3, vcc_lo
; CHECK-NEXT:    s_add_u32 s4, s4, 0xffffff00
; CHECK-NEXT:    s_addc_u32 s5, s5, -1
; CHECK-NEXT:    s_waitcnt vmcnt(15)
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:80
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:84
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:88
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:92
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:92
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:88
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:84
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:80
; CHECK-NEXT:    s_cmp_lg_u64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v19, off offset:254
; CHECK-NEXT:    global_store_byte v[0:1], v19, off offset:252
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v18, off offset:250
; CHECK-NEXT:    global_store_byte v[0:1], v18, off offset:248
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v17, off offset:246
; CHECK-NEXT:    global_store_byte v[0:1], v17, off offset:244
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v16, off offset:242
; CHECK-NEXT:    global_store_byte v[0:1], v16, off offset:240
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:96
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:100
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:104
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:108
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:108
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:104
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:100
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:96
; CHECK-NEXT:    v_lshrrev_b32_e32 v100, 24, v19
; CHECK-NEXT:    v_lshrrev_b32_e32 v19, 8, v19
; CHECK-NEXT:    v_lshrrev_b32_e32 v101, 24, v18
; CHECK-NEXT:    v_lshrrev_b32_e32 v18, 8, v18
; CHECK-NEXT:    v_lshrrev_b32_e32 v102, 24, v17
; CHECK-NEXT:    v_lshrrev_b32_e32 v17, 8, v17
; CHECK-NEXT:    v_lshrrev_b32_e32 v103, 24, v16
; CHECK-NEXT:    v_lshrrev_b32_e32 v16, 8, v16
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v23, off offset:238
; CHECK-NEXT:    global_store_byte v[0:1], v23, off offset:236
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v22, off offset:234
; CHECK-NEXT:    global_store_byte v[0:1], v22, off offset:232
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v21, off offset:230
; CHECK-NEXT:    global_store_byte v[0:1], v21, off offset:228
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v20, off offset:226
; CHECK-NEXT:    global_store_byte v[0:1], v20, off offset:224
; CHECK-NEXT:    buffer_store_dword v24, off, s[0:3], s32 offset:48
; CHECK-NEXT:    buffer_store_dword v25, off, s[0:3], s32 offset:52
; CHECK-NEXT:    buffer_store_dword v26, off, s[0:3], s32 offset:56
; CHECK-NEXT:    buffer_store_dword v27, off, s[0:3], s32 offset:60
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:60
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:56
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:52
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:48
; CHECK-NEXT:    v_lshrrev_b32_e32 v112, 24, v23
; CHECK-NEXT:    v_lshrrev_b32_e32 v23, 8, v23
; CHECK-NEXT:    v_lshrrev_b32_e32 v113, 24, v22
; CHECK-NEXT:    v_lshrrev_b32_e32 v22, 8, v22
; CHECK-NEXT:    v_lshrrev_b32_e32 v114, 24, v21
; CHECK-NEXT:    v_lshrrev_b32_e32 v21, 8, v21
; CHECK-NEXT:    v_lshrrev_b32_e32 v115, 24, v20
; CHECK-NEXT:    v_lshrrev_b32_e32 v20, 8, v20
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v27, off offset:222
; CHECK-NEXT:    global_store_byte v[0:1], v27, off offset:220
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v26, off offset:218
; CHECK-NEXT:    global_store_byte v[0:1], v26, off offset:216
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v25, off offset:214
; CHECK-NEXT:    global_store_byte v[0:1], v25, off offset:212
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v24, off offset:210
; CHECK-NEXT:    global_store_byte v[0:1], v24, off offset:208
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:64
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:68
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:72
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:76
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:76
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:72
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:68
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:64
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v31, off offset:206
; CHECK-NEXT:    global_store_byte v[0:1], v31, off offset:204
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v30, off offset:202
; CHECK-NEXT:    global_store_byte v[0:1], v30, off offset:200
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v29, off offset:198
; CHECK-NEXT:    global_store_byte v[0:1], v29, off offset:196
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v28, off offset:194
; CHECK-NEXT:    global_store_byte v[0:1], v28, off offset:192
; CHECK-NEXT:    buffer_store_dword v32, off, s[0:3], s32 offset:144
; CHECK-NEXT:    buffer_store_dword v33, off, s[0:3], s32 offset:148
; CHECK-NEXT:    buffer_store_dword v34, off, s[0:3], s32 offset:152
; CHECK-NEXT:    buffer_store_dword v35, off, s[0:3], s32 offset:156
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s32 offset:156
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:152
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:148
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:144
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v35, off offset:190
; CHECK-NEXT:    global_store_byte v[0:1], v35, off offset:188
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v34, off offset:186
; CHECK-NEXT:    global_store_byte v[0:1], v34, off offset:184
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v33, off offset:182
; CHECK-NEXT:    global_store_byte v[0:1], v33, off offset:180
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v32, off offset:178
; CHECK-NEXT:    global_store_byte v[0:1], v32, off offset:176
; CHECK-NEXT:    buffer_store_dword v36, off, s[0:3], s32 offset:160
; CHECK-NEXT:    buffer_store_dword v37, off, s[0:3], s32 offset:164
; CHECK-NEXT:    buffer_store_dword v38, off, s[0:3], s32 offset:168
; CHECK-NEXT:    buffer_store_dword v39, off, s[0:3], s32 offset:172
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v39, off, s[0:3], s32 offset:172
; CHECK-NEXT:    buffer_load_dword v38, off, s[0:3], s32 offset:168
; CHECK-NEXT:    buffer_load_dword v37, off, s[0:3], s32 offset:164
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s32 offset:160
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v39, off offset:174
; CHECK-NEXT:    global_store_byte v[0:1], v39, off offset:172
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v38, off offset:170
; CHECK-NEXT:    global_store_byte v[0:1], v38, off offset:168
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v37, off offset:166
; CHECK-NEXT:    global_store_byte v[0:1], v37, off offset:164
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v36, off offset:162
; CHECK-NEXT:    global_store_byte v[0:1], v36, off offset:160
; CHECK-NEXT:    buffer_store_dword v48, off, s[0:3], s32 offset:112
; CHECK-NEXT:    buffer_store_dword v49, off, s[0:3], s32 offset:116
; CHECK-NEXT:    buffer_store_dword v50, off, s[0:3], s32 offset:120
; CHECK-NEXT:    buffer_store_dword v51, off, s[0:3], s32 offset:124
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v51, off, s[0:3], s32 offset:124
; CHECK-NEXT:    buffer_load_dword v50, off, s[0:3], s32 offset:120
; CHECK-NEXT:    buffer_load_dword v49, off, s[0:3], s32 offset:116
; CHECK-NEXT:    buffer_load_dword v48, off, s[0:3], s32 offset:112
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v51, off offset:158
; CHECK-NEXT:    global_store_byte v[0:1], v51, off offset:156
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v50, off offset:154
; CHECK-NEXT:    global_store_byte v[0:1], v50, off offset:152
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v49, off offset:150
; CHECK-NEXT:    global_store_byte v[0:1], v49, off offset:148
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v48, off offset:146
; CHECK-NEXT:    global_store_byte v[0:1], v48, off offset:144
; CHECK-NEXT:    buffer_store_dword v52, off, s[0:3], s32 offset:128
; CHECK-NEXT:    buffer_store_dword v53, off, s[0:3], s32 offset:132
; CHECK-NEXT:    buffer_store_dword v54, off, s[0:3], s32 offset:136
; CHECK-NEXT:    buffer_store_dword v55, off, s[0:3], s32 offset:140
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v55, off, s[0:3], s32 offset:140
; CHECK-NEXT:    buffer_load_dword v54, off, s[0:3], s32 offset:136
; CHECK-NEXT:    buffer_load_dword v53, off, s[0:3], s32 offset:132
; CHECK-NEXT:    buffer_load_dword v52, off, s[0:3], s32 offset:128
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v55, off offset:142
; CHECK-NEXT:    global_store_byte v[0:1], v55, off offset:140
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v54, off offset:138
; CHECK-NEXT:    global_store_byte v[0:1], v54, off offset:136
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v53, off offset:134
; CHECK-NEXT:    global_store_byte v[0:1], v53, off offset:132
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v52, off offset:130
; CHECK-NEXT:    global_store_byte v[0:1], v52, off offset:128
; CHECK-NEXT:    buffer_store_dword v64, off, s[0:3], s32 offset:208
; CHECK-NEXT:    buffer_store_dword v65, off, s[0:3], s32 offset:212
; CHECK-NEXT:    buffer_store_dword v66, off, s[0:3], s32 offset:216
; CHECK-NEXT:    buffer_store_dword v67, off, s[0:3], s32 offset:220
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v67, off, s[0:3], s32 offset:220
; CHECK-NEXT:    buffer_load_dword v66, off, s[0:3], s32 offset:216
; CHECK-NEXT:    buffer_load_dword v65, off, s[0:3], s32 offset:212
; CHECK-NEXT:    buffer_load_dword v64, off, s[0:3], s32 offset:208
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v67, off offset:126
; CHECK-NEXT:    global_store_byte v[0:1], v67, off offset:124
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v66, off offset:122
; CHECK-NEXT:    global_store_byte v[0:1], v66, off offset:120
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v65, off offset:118
; CHECK-NEXT:    global_store_byte v[0:1], v65, off offset:116
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v64, off offset:114
; CHECK-NEXT:    global_store_byte v[0:1], v64, off offset:112
; CHECK-NEXT:    buffer_store_dword v68, off, s[0:3], s32 offset:224
; CHECK-NEXT:    buffer_store_dword v69, off, s[0:3], s32 offset:228
; CHECK-NEXT:    buffer_store_dword v70, off, s[0:3], s32 offset:232
; CHECK-NEXT:    buffer_store_dword v71, off, s[0:3], s32 offset:236
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v71, off, s[0:3], s32 offset:236
; CHECK-NEXT:    buffer_load_dword v70, off, s[0:3], s32 offset:232
; CHECK-NEXT:    buffer_load_dword v69, off, s[0:3], s32 offset:228
; CHECK-NEXT:    buffer_load_dword v68, off, s[0:3], s32 offset:224
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v71, off offset:110
; CHECK-NEXT:    global_store_byte v[0:1], v71, off offset:108
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v70, off offset:106
; CHECK-NEXT:    global_store_byte v[0:1], v70, off offset:104
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v69, off offset:102
; CHECK-NEXT:    global_store_byte v[0:1], v69, off offset:100
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v68, off offset:98
; CHECK-NEXT:    global_store_byte v[0:1], v68, off offset:96
; CHECK-NEXT:    buffer_store_dword v80, off, s[0:3], s32 offset:176
; CHECK-NEXT:    buffer_store_dword v81, off, s[0:3], s32 offset:180
; CHECK-NEXT:    buffer_store_dword v82, off, s[0:3], s32 offset:184
; CHECK-NEXT:    buffer_store_dword v83, off, s[0:3], s32 offset:188
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v83, off, s[0:3], s32 offset:188
; CHECK-NEXT:    buffer_load_dword v82, off, s[0:3], s32 offset:184
; CHECK-NEXT:    buffer_load_dword v81, off, s[0:3], s32 offset:180
; CHECK-NEXT:    buffer_load_dword v80, off, s[0:3], s32 offset:176
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v83, off offset:94
; CHECK-NEXT:    global_store_byte v[0:1], v83, off offset:92
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v82, off offset:90
; CHECK-NEXT:    global_store_byte v[0:1], v82, off offset:88
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v81, off offset:86
; CHECK-NEXT:    global_store_byte v[0:1], v81, off offset:84
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v80, off offset:82
; CHECK-NEXT:    global_store_byte v[0:1], v80, off offset:80
; CHECK-NEXT:    buffer_store_dword v84, off, s[0:3], s32 offset:192
; CHECK-NEXT:    buffer_store_dword v85, off, s[0:3], s32 offset:196
; CHECK-NEXT:    buffer_store_dword v86, off, s[0:3], s32 offset:200
; CHECK-NEXT:    buffer_store_dword v87, off, s[0:3], s32 offset:204
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v87, off, s[0:3], s32 offset:204
; CHECK-NEXT:    buffer_load_dword v86, off, s[0:3], s32 offset:200
; CHECK-NEXT:    buffer_load_dword v85, off, s[0:3], s32 offset:196
; CHECK-NEXT:    buffer_load_dword v84, off, s[0:3], s32 offset:192
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v87, off offset:78
; CHECK-NEXT:    global_store_byte v[0:1], v87, off offset:76
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v86, off offset:74
; CHECK-NEXT:    global_store_byte v[0:1], v86, off offset:72
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v85, off offset:70
; CHECK-NEXT:    global_store_byte v[0:1], v85, off offset:68
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v84, off offset:66
; CHECK-NEXT:    global_store_byte v[0:1], v84, off offset:64
; CHECK-NEXT:    buffer_store_dword v96, off, s[0:3], s32 offset:272
; CHECK-NEXT:    buffer_store_dword v97, off, s[0:3], s32 offset:276
; CHECK-NEXT:    buffer_store_dword v98, off, s[0:3], s32 offset:280
; CHECK-NEXT:    buffer_store_dword v99, off, s[0:3], s32 offset:284
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v99, off, s[0:3], s32 offset:284
; CHECK-NEXT:    buffer_load_dword v98, off, s[0:3], s32 offset:280
; CHECK-NEXT:    buffer_load_dword v97, off, s[0:3], s32 offset:276
; CHECK-NEXT:    buffer_load_dword v96, off, s[0:3], s32 offset:272
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v99, off offset:62
; CHECK-NEXT:    global_store_byte v[0:1], v99, off offset:60
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v98, off offset:58
; CHECK-NEXT:    global_store_byte v[0:1], v98, off offset:56
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v97, off offset:54
; CHECK-NEXT:    global_store_byte v[0:1], v97, off offset:52
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v96, off offset:50
; CHECK-NEXT:    global_store_byte v[0:1], v96, off offset:48
; CHECK-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:288
; CHECK-NEXT:    buffer_store_dword v13, off, s[0:3], s32 offset:292
; CHECK-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:296
; CHECK-NEXT:    buffer_store_dword v15, off, s[0:3], s32 offset:300
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:296
; CHECK-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:300
; CHECK-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:288
; CHECK-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:292
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v15, off offset:42
; CHECK-NEXT:    global_store_byte v[0:1], v15, off offset:40
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v14, off offset:46
; CHECK-NEXT:    global_store_byte v[0:1], v14, off offset:44
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v13, off offset:34
; CHECK-NEXT:    global_store_byte v[0:1], v13, off offset:32
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v12, off offset:38
; CHECK-NEXT:    global_store_byte v[0:1], v12, off offset:36
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:240
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:244
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:248
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:252
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:252
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:248
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:244
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:240
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v11, off offset:30
; CHECK-NEXT:    global_store_byte v[0:1], v11, off offset:28
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v10, off offset:26
; CHECK-NEXT:    global_store_byte v[0:1], v10, off offset:24
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v9, off offset:22
; CHECK-NEXT:    global_store_byte v[0:1], v9, off offset:20
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v8, off offset:18
; CHECK-NEXT:    global_store_byte v[0:1], v8, off offset:16
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:256
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:260
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:264
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:268
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:268
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:264
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:260
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:256
; CHECK-NEXT:    global_store_byte v[0:1], v100, off offset:255
; CHECK-NEXT:    v_lshrrev_b32_e32 v100, 24, v27
; CHECK-NEXT:    v_lshrrev_b32_e32 v27, 8, v27
; CHECK-NEXT:    global_store_byte v[0:1], v19, off offset:253
; CHECK-NEXT:    v_lshrrev_b32_e32 v19, 24, v26
; CHECK-NEXT:    v_lshrrev_b32_e32 v26, 8, v26
; CHECK-NEXT:    global_store_byte v[0:1], v101, off offset:251
; CHECK-NEXT:    v_lshrrev_b32_e32 v101, 24, v25
; CHECK-NEXT:    global_store_byte v[0:1], v27, off offset:221
; CHECK-NEXT:    v_lshrrev_b32_e32 v27, 24, v50
; CHECK-NEXT:    v_lshrrev_b32_e32 v50, 8, v50
; CHECK-NEXT:    v_lshrrev_b32_e32 v25, 8, v25
; CHECK-NEXT:    global_store_byte v[0:1], v18, off offset:249
; CHECK-NEXT:    v_lshrrev_b32_e32 v18, 24, v24
; CHECK-NEXT:    v_lshrrev_b32_e32 v24, 8, v24
; CHECK-NEXT:    global_store_byte v[0:1], v102, off offset:247
; CHECK-NEXT:    v_lshrrev_b32_e32 v102, 24, v31
; CHECK-NEXT:    v_lshrrev_b32_e32 v31, 8, v31
; CHECK-NEXT:    global_store_byte v[0:1], v17, off offset:245
; CHECK-NEXT:    v_lshrrev_b32_e32 v17, 24, v30
; CHECK-NEXT:    v_lshrrev_b32_e32 v30, 8, v30
; CHECK-NEXT:    global_store_byte v[0:1], v103, off offset:243
; CHECK-NEXT:    v_lshrrev_b32_e32 v103, 24, v29
; CHECK-NEXT:    v_lshrrev_b32_e32 v29, 8, v29
; CHECK-NEXT:    global_store_byte v[0:1], v16, off offset:241
; CHECK-NEXT:    v_lshrrev_b32_e32 v16, 24, v28
; CHECK-NEXT:    v_lshrrev_b32_e32 v28, 8, v28
; CHECK-NEXT:    global_store_byte v[0:1], v112, off offset:239
; CHECK-NEXT:    v_lshrrev_b32_e32 v112, 24, v35
; CHECK-NEXT:    v_lshrrev_b32_e32 v35, 8, v35
; CHECK-NEXT:    global_store_byte v[0:1], v23, off offset:237
; CHECK-NEXT:    v_lshrrev_b32_e32 v23, 24, v34
; CHECK-NEXT:    v_lshrrev_b32_e32 v34, 8, v34
; CHECK-NEXT:    global_store_byte v[0:1], v113, off offset:235
; CHECK-NEXT:    v_lshrrev_b32_e32 v113, 24, v33
; CHECK-NEXT:    v_lshrrev_b32_e32 v33, 8, v33
; CHECK-NEXT:    global_store_byte v[0:1], v22, off offset:233
; CHECK-NEXT:    v_lshrrev_b32_e32 v22, 24, v32
; CHECK-NEXT:    v_lshrrev_b32_e32 v32, 8, v32
; CHECK-NEXT:    global_store_byte v[0:1], v114, off offset:231
; CHECK-NEXT:    v_lshrrev_b32_e32 v114, 24, v39
; CHECK-NEXT:    v_lshrrev_b32_e32 v39, 8, v39
; CHECK-NEXT:    global_store_byte v[0:1], v21, off offset:229
; CHECK-NEXT:    v_lshrrev_b32_e32 v21, 24, v38
; CHECK-NEXT:    v_lshrrev_b32_e32 v38, 8, v38
; CHECK-NEXT:    global_store_byte v[0:1], v115, off offset:227
; CHECK-NEXT:    v_lshrrev_b32_e32 v115, 24, v37
; CHECK-NEXT:    v_lshrrev_b32_e32 v37, 8, v37
; CHECK-NEXT:    global_store_byte v[0:1], v20, off offset:225
; CHECK-NEXT:    v_lshrrev_b32_e32 v20, 24, v36
; CHECK-NEXT:    v_lshrrev_b32_e32 v36, 8, v36
; CHECK-NEXT:    global_store_byte v[0:1], v100, off offset:223
; CHECK-NEXT:    v_lshrrev_b32_e32 v100, 24, v51
; CHECK-NEXT:    v_lshrrev_b32_e32 v51, 8, v51
; CHECK-NEXT:    global_store_byte v[0:1], v19, off offset:219
; CHECK-NEXT:    v_lshrrev_b32_e32 v19, 24, v49
; CHECK-NEXT:    v_lshrrev_b32_e32 v49, 8, v49
; CHECK-NEXT:    global_store_byte v[0:1], v26, off offset:217
; CHECK-NEXT:    v_lshrrev_b32_e32 v26, 24, v48
; CHECK-NEXT:    v_lshrrev_b32_e32 v48, 8, v48
; CHECK-NEXT:    global_store_byte v[0:1], v101, off offset:215
; CHECK-NEXT:    v_lshrrev_b32_e32 v101, 24, v55
; CHECK-NEXT:    global_store_byte v[0:1], v50, off offset:153
; CHECK-NEXT:    v_lshrrev_b32_e32 v50, 24, v8
; CHECK-NEXT:    v_lshrrev_b32_e32 v8, 8, v8
; CHECK-NEXT:    v_lshrrev_b32_e32 v55, 8, v55
; CHECK-NEXT:    global_store_byte v[0:1], v25, off offset:213
; CHECK-NEXT:    v_lshrrev_b32_e32 v25, 24, v54
; CHECK-NEXT:    v_lshrrev_b32_e32 v54, 8, v54
; CHECK-NEXT:    global_store_byte v[0:1], v18, off offset:211
; CHECK-NEXT:    v_lshrrev_b32_e32 v18, 24, v53
; CHECK-NEXT:    v_lshrrev_b32_e32 v53, 8, v53
; CHECK-NEXT:    global_store_byte v[0:1], v24, off offset:209
; CHECK-NEXT:    v_lshrrev_b32_e32 v24, 24, v52
; CHECK-NEXT:    v_lshrrev_b32_e32 v52, 8, v52
; CHECK-NEXT:    global_store_byte v[0:1], v102, off offset:207
; CHECK-NEXT:    v_lshrrev_b32_e32 v102, 24, v67
; CHECK-NEXT:    v_lshrrev_b32_e32 v67, 8, v67
; CHECK-NEXT:    global_store_byte v[0:1], v31, off offset:205
; CHECK-NEXT:    v_lshrrev_b32_e32 v31, 24, v66
; CHECK-NEXT:    v_lshrrev_b32_e32 v66, 8, v66
; CHECK-NEXT:    global_store_byte v[0:1], v17, off offset:203
; CHECK-NEXT:    v_lshrrev_b32_e32 v17, 24, v65
; CHECK-NEXT:    v_lshrrev_b32_e32 v65, 8, v65
; CHECK-NEXT:    global_store_byte v[0:1], v30, off offset:201
; CHECK-NEXT:    v_lshrrev_b32_e32 v30, 24, v64
; CHECK-NEXT:    v_lshrrev_b32_e32 v64, 8, v64
; CHECK-NEXT:    global_store_byte v[0:1], v103, off offset:199
; CHECK-NEXT:    v_lshrrev_b32_e32 v103, 24, v71
; CHECK-NEXT:    v_lshrrev_b32_e32 v71, 8, v71
; CHECK-NEXT:    global_store_byte v[0:1], v29, off offset:197
; CHECK-NEXT:    v_lshrrev_b32_e32 v29, 24, v70
; CHECK-NEXT:    v_lshrrev_b32_e32 v70, 8, v70
; CHECK-NEXT:    global_store_byte v[0:1], v16, off offset:195
; CHECK-NEXT:    v_lshrrev_b32_e32 v16, 24, v69
; CHECK-NEXT:    v_lshrrev_b32_e32 v69, 8, v69
; CHECK-NEXT:    global_store_byte v[0:1], v28, off offset:193
; CHECK-NEXT:    v_lshrrev_b32_e32 v28, 24, v68
; CHECK-NEXT:    v_lshrrev_b32_e32 v68, 8, v68
; CHECK-NEXT:    global_store_byte v[0:1], v112, off offset:191
; CHECK-NEXT:    v_lshrrev_b32_e32 v112, 24, v83
; CHECK-NEXT:    v_lshrrev_b32_e32 v83, 8, v83
; CHECK-NEXT:    global_store_byte v[0:1], v35, off offset:189
; CHECK-NEXT:    v_lshrrev_b32_e32 v35, 24, v82
; CHECK-NEXT:    v_lshrrev_b32_e32 v82, 8, v82
; CHECK-NEXT:    global_store_byte v[0:1], v23, off offset:187
; CHECK-NEXT:    v_lshrrev_b32_e32 v23, 24, v81
; CHECK-NEXT:    v_lshrrev_b32_e32 v81, 8, v81
; CHECK-NEXT:    global_store_byte v[0:1], v34, off offset:185
; CHECK-NEXT:    v_lshrrev_b32_e32 v34, 24, v80
; CHECK-NEXT:    v_lshrrev_b32_e32 v80, 8, v80
; CHECK-NEXT:    global_store_byte v[0:1], v113, off offset:183
; CHECK-NEXT:    v_lshrrev_b32_e32 v113, 24, v87
; CHECK-NEXT:    v_lshrrev_b32_e32 v87, 8, v87
; CHECK-NEXT:    global_store_byte v[0:1], v33, off offset:181
; CHECK-NEXT:    v_lshrrev_b32_e32 v33, 24, v86
; CHECK-NEXT:    v_lshrrev_b32_e32 v86, 8, v86
; CHECK-NEXT:    global_store_byte v[0:1], v22, off offset:179
; CHECK-NEXT:    v_lshrrev_b32_e32 v22, 24, v85
; CHECK-NEXT:    v_lshrrev_b32_e32 v85, 8, v85
; CHECK-NEXT:    global_store_byte v[0:1], v32, off offset:177
; CHECK-NEXT:    v_lshrrev_b32_e32 v32, 24, v84
; CHECK-NEXT:    v_lshrrev_b32_e32 v84, 8, v84
; CHECK-NEXT:    global_store_byte v[0:1], v114, off offset:175
; CHECK-NEXT:    v_lshrrev_b32_e32 v114, 24, v99
; CHECK-NEXT:    v_lshrrev_b32_e32 v99, 8, v99
; CHECK-NEXT:    global_store_byte v[0:1], v39, off offset:173
; CHECK-NEXT:    v_lshrrev_b32_e32 v39, 24, v98
; CHECK-NEXT:    v_lshrrev_b32_e32 v98, 8, v98
; CHECK-NEXT:    global_store_byte v[0:1], v21, off offset:171
; CHECK-NEXT:    v_lshrrev_b32_e32 v21, 24, v97
; CHECK-NEXT:    v_lshrrev_b32_e32 v97, 8, v97
; CHECK-NEXT:    global_store_byte v[0:1], v38, off offset:169
; CHECK-NEXT:    v_lshrrev_b32_e32 v38, 24, v96
; CHECK-NEXT:    v_lshrrev_b32_e32 v96, 8, v96
; CHECK-NEXT:    global_store_byte v[0:1], v115, off offset:167
; CHECK-NEXT:    v_lshrrev_b32_e32 v115, 24, v15
; CHECK-NEXT:    v_lshrrev_b32_e32 v15, 8, v15
; CHECK-NEXT:    global_store_byte v[0:1], v37, off offset:165
; CHECK-NEXT:    v_lshrrev_b32_e32 v37, 24, v14
; CHECK-NEXT:    v_lshrrev_b32_e32 v14, 8, v14
; CHECK-NEXT:    global_store_byte v[0:1], v20, off offset:163
; CHECK-NEXT:    v_lshrrev_b32_e32 v20, 24, v13
; CHECK-NEXT:    v_lshrrev_b32_e32 v13, 8, v13
; CHECK-NEXT:    global_store_byte v[0:1], v36, off offset:161
; CHECK-NEXT:    v_lshrrev_b32_e32 v36, 24, v12
; CHECK-NEXT:    v_lshrrev_b32_e32 v12, 8, v12
; CHECK-NEXT:    global_store_byte v[0:1], v100, off offset:159
; CHECK-NEXT:    v_lshrrev_b32_e32 v100, 24, v11
; CHECK-NEXT:    v_lshrrev_b32_e32 v11, 8, v11
; CHECK-NEXT:    global_store_byte v[0:1], v51, off offset:157
; CHECK-NEXT:    v_lshrrev_b32_e32 v51, 24, v10
; CHECK-NEXT:    v_lshrrev_b32_e32 v10, 8, v10
; CHECK-NEXT:    global_store_byte v[0:1], v27, off offset:155
; CHECK-NEXT:    v_lshrrev_b32_e32 v27, 24, v9
; CHECK-NEXT:    v_lshrrev_b32_e32 v9, 8, v9
; CHECK-NEXT:    global_store_byte v[0:1], v19, off offset:151
; CHECK-NEXT:    global_store_byte v[0:1], v49, off offset:149
; CHECK-NEXT:    global_store_byte v[0:1], v26, off offset:147
; CHECK-NEXT:    global_store_byte v[0:1], v48, off offset:145
; CHECK-NEXT:    global_store_byte v[0:1], v101, off offset:143
; CHECK-NEXT:    global_store_byte v[0:1], v55, off offset:141
; CHECK-NEXT:    global_store_byte v[0:1], v25, off offset:139
; CHECK-NEXT:    global_store_byte v[0:1], v54, off offset:137
; CHECK-NEXT:    global_store_byte v[0:1], v18, off offset:135
; CHECK-NEXT:    global_store_byte v[0:1], v53, off offset:133
; CHECK-NEXT:    global_store_byte v[0:1], v24, off offset:131
; CHECK-NEXT:    global_store_byte v[0:1], v52, off offset:129
; CHECK-NEXT:    global_store_byte v[0:1], v102, off offset:127
; CHECK-NEXT:    global_store_byte v[0:1], v67, off offset:125
; CHECK-NEXT:    global_store_byte v[0:1], v31, off offset:123
; CHECK-NEXT:    global_store_byte v[0:1], v66, off offset:121
; CHECK-NEXT:    global_store_byte v[0:1], v17, off offset:119
; CHECK-NEXT:    global_store_byte v[0:1], v65, off offset:117
; CHECK-NEXT:    global_store_byte v[0:1], v30, off offset:115
; CHECK-NEXT:    global_store_byte v[0:1], v64, off offset:113
; CHECK-NEXT:    global_store_byte v[0:1], v103, off offset:111
; CHECK-NEXT:    global_store_byte v[0:1], v71, off offset:109
; CHECK-NEXT:    global_store_byte v[0:1], v29, off offset:107
; CHECK-NEXT:    global_store_byte v[0:1], v70, off offset:105
; CHECK-NEXT:    global_store_byte v[0:1], v16, off offset:103
; CHECK-NEXT:    global_store_byte v[0:1], v69, off offset:101
; CHECK-NEXT:    global_store_byte v[0:1], v28, off offset:99
; CHECK-NEXT:    global_store_byte v[0:1], v68, off offset:97
; CHECK-NEXT:    global_store_byte v[0:1], v112, off offset:95
; CHECK-NEXT:    global_store_byte v[0:1], v83, off offset:93
; CHECK-NEXT:    global_store_byte v[0:1], v35, off offset:91
; CHECK-NEXT:    global_store_byte v[0:1], v82, off offset:89
; CHECK-NEXT:    global_store_byte v[0:1], v23, off offset:87
; CHECK-NEXT:    global_store_byte v[0:1], v81, off offset:85
; CHECK-NEXT:    global_store_byte v[0:1], v34, off offset:83
; CHECK-NEXT:    global_store_byte v[0:1], v80, off offset:81
; CHECK-NEXT:    global_store_byte v[0:1], v113, off offset:79
; CHECK-NEXT:    global_store_byte v[0:1], v87, off offset:77
; CHECK-NEXT:    global_store_byte v[0:1], v33, off offset:75
; CHECK-NEXT:    global_store_byte v[0:1], v86, off offset:73
; CHECK-NEXT:    global_store_byte v[0:1], v22, off offset:71
; CHECK-NEXT:    global_store_byte v[0:1], v85, off offset:69
; CHECK-NEXT:    global_store_byte v[0:1], v32, off offset:67
; CHECK-NEXT:    global_store_byte v[0:1], v84, off offset:65
; CHECK-NEXT:    global_store_byte v[0:1], v114, off offset:63
; CHECK-NEXT:    global_store_byte v[0:1], v99, off offset:61
; CHECK-NEXT:    global_store_byte v[0:1], v39, off offset:59
; CHECK-NEXT:    global_store_byte v[0:1], v98, off offset:57
; CHECK-NEXT:    global_store_byte v[0:1], v21, off offset:55
; CHECK-NEXT:    global_store_byte v[0:1], v97, off offset:53
; CHECK-NEXT:    global_store_byte v[0:1], v38, off offset:51
; CHECK-NEXT:    global_store_byte v[0:1], v96, off offset:49
; CHECK-NEXT:    global_store_byte v[0:1], v115, off offset:43
; CHECK-NEXT:    global_store_byte v[0:1], v15, off offset:41
; CHECK-NEXT:    global_store_byte v[0:1], v37, off offset:47
; CHECK-NEXT:    global_store_byte v[0:1], v14, off offset:45
; CHECK-NEXT:    global_store_byte v[0:1], v20, off offset:35
; CHECK-NEXT:    global_store_byte v[0:1], v13, off offset:33
; CHECK-NEXT:    global_store_byte v[0:1], v36, off offset:39
; CHECK-NEXT:    global_store_byte v[0:1], v12, off offset:37
; CHECK-NEXT:    global_store_byte v[0:1], v100, off offset:31
; CHECK-NEXT:    global_store_byte v[0:1], v11, off offset:29
; CHECK-NEXT:    global_store_byte v[0:1], v51, off offset:27
; CHECK-NEXT:    global_store_byte v[0:1], v10, off offset:25
; CHECK-NEXT:    global_store_byte v[0:1], v27, off offset:23
; CHECK-NEXT:    global_store_byte v[0:1], v9, off offset:21
; CHECK-NEXT:    global_store_byte v[0:1], v50, off offset:19
; CHECK-NEXT:    global_store_byte v[0:1], v8, off offset:17
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v7, off offset:14
; CHECK-NEXT:    global_store_byte v[0:1], v7, off offset:12
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v6, off offset:10
; CHECK-NEXT:    global_store_byte v[0:1], v6, off offset:8
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v5, off offset:6
; CHECK-NEXT:    global_store_byte v[0:1], v5, off offset:4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[0:1], v4, off offset:2
; CHECK-NEXT:    global_store_byte v[0:1], v4, off
; CHECK-NEXT:    v_lshrrev_b32_e32 v8, 24, v7
; CHECK-NEXT:    v_lshrrev_b32_e32 v7, 8, v7
; CHECK-NEXT:    v_lshrrev_b32_e32 v9, 24, v6
; CHECK-NEXT:    v_lshrrev_b32_e32 v6, 8, v6
; CHECK-NEXT:    v_lshrrev_b32_e32 v10, 24, v5
; CHECK-NEXT:    v_lshrrev_b32_e32 v5, 8, v5
; CHECK-NEXT:    v_lshrrev_b32_e32 v11, 24, v4
; CHECK-NEXT:    v_lshrrev_b32_e32 v4, 8, v4
; CHECK-NEXT:    global_store_byte v[0:1], v8, off offset:15
; CHECK-NEXT:    global_store_byte v[0:1], v7, off offset:13
; CHECK-NEXT:    global_store_byte v[0:1], v9, off offset:11
; CHECK-NEXT:    global_store_byte v[0:1], v6, off offset:9
; CHECK-NEXT:    global_store_byte v[0:1], v10, off offset:7
; CHECK-NEXT:    global_store_byte v[0:1], v5, off offset:5
; CHECK-NEXT:    global_store_byte v[0:1], v11, off offset:3
; CHECK-NEXT:    global_store_byte v[0:1], v4, off offset:1
; CHECK-NEXT:    v_add_co_u32 v0, vcc_lo, 0x100, v0
; CHECK-NEXT:    v_add_co_ci_u32_e64 v1, null, 0, v1, vcc_lo
; CHECK-NEXT:    s_cbranch_scc1 .LBB0_2
; CHECK-NEXT:  .LBB0_3: ; %Flow17
; CHECK-NEXT:    s_andn2_saveexec_b32 s6, s6
; CHECK-NEXT:    s_cbranch_execz .LBB0_6
; CHECK-NEXT:  ; %bb.4: ; %memmove_bwd_loop.preheader
; CHECK-NEXT:    v_add_co_u32 v12, vcc_lo, 0x700, v0
; CHECK-NEXT:    v_add_co_ci_u32_e64 v13, null, 0, v1, vcc_lo
; CHECK-NEXT:    v_add_co_u32 v14, vcc_lo, 0x700, v2
; CHECK-NEXT:    v_add_co_ci_u32_e64 v15, null, 0, v3, vcc_lo
; CHECK-NEXT:    s_movk_i32 s4, 0xf800
; CHECK-NEXT:    s_mov_b32 s5, -1
; CHECK-NEXT:  .LBB0_5: ; %memmove_bwd_loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_clause 0xf
; CHECK-NEXT:    global_load_dwordx4 v[16:19], v[14:15], off offset:240
; CHECK-NEXT:    global_load_dwordx4 v[20:23], v[14:15], off offset:224
; CHECK-NEXT:    global_load_dwordx4 v[0:3], v[14:15], off
; CHECK-NEXT:    global_load_dwordx4 v[4:7], v[14:15], off offset:16
; CHECK-NEXT:    global_load_dwordx4 v[8:11], v[14:15], off offset:32
; CHECK-NEXT:    global_load_dwordx4 v[100:103], v[14:15], off offset:48
; CHECK-NEXT:    global_load_dwordx4 v[112:115], v[14:15], off offset:64
; CHECK-NEXT:    global_load_dwordx4 v[116:119], v[14:15], off offset:80
; CHECK-NEXT:    global_load_dwordx4 v[40:43], v[14:15], off offset:96
; CHECK-NEXT:    global_load_dwordx4 v[28:31], v[14:15], off offset:112
; CHECK-NEXT:    global_load_dwordx4 v[34:37], v[14:15], off offset:128
; CHECK-NEXT:    global_load_dwordx4 v[44:47], v[14:15], off offset:144
; CHECK-NEXT:    global_load_dwordx4 v[54:57], v[14:15], off offset:160
; CHECK-NEXT:    global_load_dwordx4 v[68:71], v[14:15], off offset:176
; CHECK-NEXT:    global_load_dwordx4 v[82:85], v[14:15], off offset:192
; CHECK-NEXT:    global_load_dwordx4 v[64:67], v[14:15], off offset:208
; CHECK-NEXT:    v_add_co_u32 v14, vcc_lo, 0xffffff00, v14
; CHECK-NEXT:    v_add_co_ci_u32_e64 v15, null, -1, v15, vcc_lo
; CHECK-NEXT:    s_add_u32 s4, s4, 0x100
; CHECK-NEXT:    s_addc_u32 s5, s5, 0
; CHECK-NEXT:    s_waitcnt vmcnt(15)
; CHECK-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:336
; CHECK-NEXT:    buffer_store_dword v17, off, s[0:3], s32 offset:340
; CHECK-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:344
; CHECK-NEXT:    buffer_store_dword v19, off, s[0:3], s32 offset:348
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:348
; CHECK-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:344
; CHECK-NEXT:    buffer_load_dword v27, off, s[0:3], s32 offset:340
; CHECK-NEXT:    buffer_load_dword v26, off, s[0:3], s32 offset:336
; CHECK-NEXT:    s_cmp_eq_u64 s[4:5], 0
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v33, off offset:254
; CHECK-NEXT:    global_store_byte v[12:13], v33, off offset:252
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v32, off offset:250
; CHECK-NEXT:    global_store_byte v[12:13], v32, off offset:248
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v27, off offset:246
; CHECK-NEXT:    global_store_byte v[12:13], v27, off offset:244
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v26, off offset:242
; CHECK-NEXT:    global_store_byte v[12:13], v26, off offset:240
; CHECK-NEXT:    buffer_store_dword v20, off, s[0:3], s32 offset:352
; CHECK-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:356
; CHECK-NEXT:    buffer_store_dword v22, off, s[0:3], s32 offset:360
; CHECK-NEXT:    buffer_store_dword v23, off, s[0:3], s32 offset:364
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v53, off, s[0:3], s32 offset:364
; CHECK-NEXT:    buffer_load_dword v52, off, s[0:3], s32 offset:360
; CHECK-NEXT:    buffer_load_dword v51, off, s[0:3], s32 offset:356
; CHECK-NEXT:    buffer_load_dword v50, off, s[0:3], s32 offset:352
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v53, off offset:238
; CHECK-NEXT:    global_store_byte v[12:13], v53, off offset:236
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v52, off offset:234
; CHECK-NEXT:    global_store_byte v[12:13], v52, off offset:232
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v51, off offset:230
; CHECK-NEXT:    global_store_byte v[12:13], v51, off offset:228
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v50, off offset:226
; CHECK-NEXT:    global_store_byte v[12:13], v50, off offset:224
; CHECK-NEXT:    buffer_store_dword v64, off, s[0:3], s32 offset:304
; CHECK-NEXT:    buffer_store_dword v65, off, s[0:3], s32 offset:308
; CHECK-NEXT:    buffer_store_dword v66, off, s[0:3], s32 offset:312
; CHECK-NEXT:    buffer_store_dword v67, off, s[0:3], s32 offset:316
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v81, off, s[0:3], s32 offset:316
; CHECK-NEXT:    buffer_load_dword v80, off, s[0:3], s32 offset:312
; CHECK-NEXT:    buffer_load_dword v67, off, s[0:3], s32 offset:308
; CHECK-NEXT:    buffer_load_dword v66, off, s[0:3], s32 offset:304
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v81, off offset:222
; CHECK-NEXT:    global_store_byte v[12:13], v81, off offset:220
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v80, off offset:218
; CHECK-NEXT:    global_store_byte v[12:13], v80, off offset:216
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v67, off offset:214
; CHECK-NEXT:    global_store_byte v[12:13], v67, off offset:212
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v66, off offset:210
; CHECK-NEXT:    global_store_byte v[12:13], v66, off offset:208
; CHECK-NEXT:    buffer_store_dword v82, off, s[0:3], s32 offset:320
; CHECK-NEXT:    buffer_store_dword v83, off, s[0:3], s32 offset:324
; CHECK-NEXT:    buffer_store_dword v84, off, s[0:3], s32 offset:328
; CHECK-NEXT:    buffer_store_dword v85, off, s[0:3], s32 offset:332
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v98, off, s[0:3], s32 offset:332
; CHECK-NEXT:    buffer_load_dword v87, off, s[0:3], s32 offset:328
; CHECK-NEXT:    buffer_load_dword v86, off, s[0:3], s32 offset:324
; CHECK-NEXT:    buffer_load_dword v82, off, s[0:3], s32 offset:320
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v98, off offset:206
; CHECK-NEXT:    global_store_byte v[12:13], v98, off offset:204
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v87, off offset:202
; CHECK-NEXT:    global_store_byte v[12:13], v87, off offset:200
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v86, off offset:198
; CHECK-NEXT:    global_store_byte v[12:13], v86, off offset:196
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v82, off offset:194
; CHECK-NEXT:    global_store_byte v[12:13], v82, off offset:192
; CHECK-NEXT:    buffer_store_dword v68, off, s[0:3], s32 offset:400
; CHECK-NEXT:    buffer_store_dword v69, off, s[0:3], s32 offset:404
; CHECK-NEXT:    buffer_store_dword v70, off, s[0:3], s32 offset:408
; CHECK-NEXT:    buffer_store_dword v71, off, s[0:3], s32 offset:412
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v99, off, s[0:3], s32 offset:412
; CHECK-NEXT:    buffer_load_dword v96, off, s[0:3], s32 offset:408
; CHECK-NEXT:    buffer_load_dword v83, off, s[0:3], s32 offset:404
; CHECK-NEXT:    buffer_load_dword v68, off, s[0:3], s32 offset:400
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v99, off offset:190
; CHECK-NEXT:    global_store_byte v[12:13], v99, off offset:188
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v96, off offset:186
; CHECK-NEXT:    global_store_byte v[12:13], v96, off offset:184
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v83, off offset:182
; CHECK-NEXT:    global_store_byte v[12:13], v83, off offset:180
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v68, off offset:178
; CHECK-NEXT:    global_store_byte v[12:13], v68, off offset:176
; CHECK-NEXT:    buffer_store_dword v54, off, s[0:3], s32 offset:416
; CHECK-NEXT:    buffer_store_dword v55, off, s[0:3], s32 offset:420
; CHECK-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:424
; CHECK-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:428
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v97, off, s[0:3], s32 offset:428
; CHECK-NEXT:    buffer_load_dword v84, off, s[0:3], s32 offset:424
; CHECK-NEXT:    buffer_load_dword v69, off, s[0:3], s32 offset:420
; CHECK-NEXT:    buffer_load_dword v54, off, s[0:3], s32 offset:416
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v97, off offset:174
; CHECK-NEXT:    global_store_byte v[12:13], v97, off offset:172
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v84, off offset:170
; CHECK-NEXT:    global_store_byte v[12:13], v84, off offset:168
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v69, off offset:166
; CHECK-NEXT:    global_store_byte v[12:13], v69, off offset:164
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v54, off offset:162
; CHECK-NEXT:    global_store_byte v[12:13], v54, off offset:160
; CHECK-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:368
; CHECK-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:372
; CHECK-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:376
; CHECK-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:380
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v85, off, s[0:3], s32 offset:380
; CHECK-NEXT:    buffer_load_dword v70, off, s[0:3], s32 offset:376
; CHECK-NEXT:    buffer_load_dword v55, off, s[0:3], s32 offset:372
; CHECK-NEXT:    buffer_load_dword v38, off, s[0:3], s32 offset:368
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v85, off offset:158
; CHECK-NEXT:    global_store_byte v[12:13], v85, off offset:156
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v70, off offset:154
; CHECK-NEXT:    global_store_byte v[12:13], v70, off offset:152
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v55, off offset:150
; CHECK-NEXT:    global_store_byte v[12:13], v55, off offset:148
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v38, off offset:146
; CHECK-NEXT:    global_store_byte v[12:13], v38, off offset:144
; CHECK-NEXT:    buffer_store_dword v34, off, s[0:3], s32 offset:384
; CHECK-NEXT:    buffer_store_dword v35, off, s[0:3], s32 offset:388
; CHECK-NEXT:    buffer_store_dword v36, off, s[0:3], s32 offset:392
; CHECK-NEXT:    buffer_store_dword v37, off, s[0:3], s32 offset:396
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v71, off, s[0:3], s32 offset:396
; CHECK-NEXT:    buffer_load_dword v64, off, s[0:3], s32 offset:392
; CHECK-NEXT:    buffer_load_dword v39, off, s[0:3], s32 offset:388
; CHECK-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:384
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v71, off offset:142
; CHECK-NEXT:    global_store_byte v[12:13], v71, off offset:140
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v64, off offset:138
; CHECK-NEXT:    global_store_byte v[12:13], v64, off offset:136
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v39, off offset:134
; CHECK-NEXT:    global_store_byte v[12:13], v39, off offset:132
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v34, off offset:130
; CHECK-NEXT:    global_store_byte v[12:13], v34, off offset:128
; CHECK-NEXT:    buffer_store_dword v28, off, s[0:3], s32 offset:464
; CHECK-NEXT:    buffer_store_dword v29, off, s[0:3], s32 offset:468
; CHECK-NEXT:    buffer_store_dword v30, off, s[0:3], s32 offset:472
; CHECK-NEXT:    buffer_store_dword v31, off, s[0:3], s32 offset:476
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v65, off, s[0:3], s32 offset:476
; CHECK-NEXT:    buffer_load_dword v48, off, s[0:3], s32 offset:472
; CHECK-NEXT:    buffer_load_dword v35, off, s[0:3], s32 offset:468
; CHECK-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:464
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v65, off offset:126
; CHECK-NEXT:    global_store_byte v[12:13], v65, off offset:124
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v48, off offset:122
; CHECK-NEXT:    global_store_byte v[12:13], v48, off offset:120
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v35, off offset:118
; CHECK-NEXT:    global_store_byte v[12:13], v35, off offset:116
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v28, off offset:114
; CHECK-NEXT:    global_store_byte v[12:13], v28, off offset:112
; CHECK-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:480
; CHECK-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:484
; CHECK-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:488
; CHECK-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:492
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v49, off, s[0:3], s32 offset:492
; CHECK-NEXT:    buffer_load_dword v36, off, s[0:3], s32 offset:488
; CHECK-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:484
; CHECK-NEXT:    buffer_load_dword v22, off, s[0:3], s32 offset:480
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v49, off offset:110
; CHECK-NEXT:    global_store_byte v[12:13], v49, off offset:108
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v36, off offset:106
; CHECK-NEXT:    global_store_byte v[12:13], v36, off offset:104
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v29, off offset:102
; CHECK-NEXT:    global_store_byte v[12:13], v29, off offset:100
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v22, off offset:98
; CHECK-NEXT:    global_store_byte v[12:13], v22, off offset:96
; CHECK-NEXT:    buffer_store_dword v116, off, s[0:3], s32 offset:432
; CHECK-NEXT:    buffer_store_dword v117, off, s[0:3], s32 offset:436
; CHECK-NEXT:    buffer_store_dword v118, off, s[0:3], s32 offset:440
; CHECK-NEXT:    buffer_store_dword v119, off, s[0:3], s32 offset:444
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v37, off, s[0:3], s32 offset:444
; CHECK-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:440
; CHECK-NEXT:    buffer_load_dword v23, off, s[0:3], s32 offset:436
; CHECK-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:432
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v37, off offset:94
; CHECK-NEXT:    global_store_byte v[12:13], v37, off offset:92
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v30, off offset:90
; CHECK-NEXT:    global_store_byte v[12:13], v30, off offset:88
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v23, off offset:86
; CHECK-NEXT:    global_store_byte v[12:13], v23, off offset:84
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v19, off offset:82
; CHECK-NEXT:    global_store_byte v[12:13], v19, off offset:80
; CHECK-NEXT:    buffer_store_dword v112, off, s[0:3], s32 offset:448
; CHECK-NEXT:    buffer_store_dword v113, off, s[0:3], s32 offset:452
; CHECK-NEXT:    buffer_store_dword v114, off, s[0:3], s32 offset:456
; CHECK-NEXT:    buffer_store_dword v115, off, s[0:3], s32 offset:460
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:460
; CHECK-NEXT:    buffer_load_dword v24, off, s[0:3], s32 offset:456
; CHECK-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:452
; CHECK-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:448
; CHECK-NEXT:    v_lshrrev_b32_e32 v112, 24, v53
; CHECK-NEXT:    v_lshrrev_b32_e32 v53, 8, v53
; CHECK-NEXT:    v_lshrrev_b32_e32 v113, 24, v52
; CHECK-NEXT:    v_lshrrev_b32_e32 v52, 8, v52
; CHECK-NEXT:    v_lshrrev_b32_e32 v114, 24, v51
; CHECK-NEXT:    v_lshrrev_b32_e32 v51, 8, v51
; CHECK-NEXT:    v_lshrrev_b32_e32 v115, 24, v50
; CHECK-NEXT:    v_lshrrev_b32_e32 v50, 8, v50
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v31, off offset:78
; CHECK-NEXT:    global_store_byte v[12:13], v31, off offset:76
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v24, off offset:74
; CHECK-NEXT:    global_store_byte v[12:13], v24, off offset:72
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v20, off offset:70
; CHECK-NEXT:    global_store_byte v[12:13], v20, off offset:68
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v17, off offset:66
; CHECK-NEXT:    global_store_byte v[12:13], v17, off offset:64
; CHECK-NEXT:    buffer_store_dword v100, off, s[0:3], s32 offset:528
; CHECK-NEXT:    buffer_store_dword v101, off, s[0:3], s32 offset:532
; CHECK-NEXT:    buffer_store_dword v102, off, s[0:3], s32 offset:536
; CHECK-NEXT:    buffer_store_dword v103, off, s[0:3], s32 offset:540
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v25, off, s[0:3], s32 offset:540
; CHECK-NEXT:    buffer_load_dword v21, off, s[0:3], s32 offset:536
; CHECK-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:532
; CHECK-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:528
; CHECK-NEXT:    v_lshrrev_b32_e32 v100, 24, v33
; CHECK-NEXT:    v_lshrrev_b32_e32 v33, 8, v33
; CHECK-NEXT:    v_lshrrev_b32_e32 v101, 24, v32
; CHECK-NEXT:    v_lshrrev_b32_e32 v32, 8, v32
; CHECK-NEXT:    v_lshrrev_b32_e32 v102, 24, v27
; CHECK-NEXT:    v_lshrrev_b32_e32 v27, 8, v27
; CHECK-NEXT:    v_lshrrev_b32_e32 v103, 24, v26
; CHECK-NEXT:    v_lshrrev_b32_e32 v26, 8, v26
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v25, off offset:62
; CHECK-NEXT:    global_store_byte v[12:13], v25, off offset:60
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v21, off offset:58
; CHECK-NEXT:    global_store_byte v[12:13], v21, off offset:56
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v18, off offset:54
; CHECK-NEXT:    global_store_byte v[12:13], v18, off offset:52
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v16, off offset:50
; CHECK-NEXT:    global_store_byte v[12:13], v16, off offset:48
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 offset:544
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:548
; CHECK-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:552
; CHECK-NEXT:    buffer_store_dword v11, off, s[0:3], s32 offset:556
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:552
; CHECK-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:556
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:544
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:548
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v11, off offset:42
; CHECK-NEXT:    global_store_byte v[12:13], v11, off offset:40
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v10, off offset:46
; CHECK-NEXT:    global_store_byte v[12:13], v10, off offset:44
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v9, off offset:34
; CHECK-NEXT:    global_store_byte v[12:13], v9, off offset:32
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v8, off offset:38
; CHECK-NEXT:    global_store_byte v[12:13], v8, off offset:36
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:496
; CHECK-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:500
; CHECK-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:504
; CHECK-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:508
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:508
; CHECK-NEXT:    buffer_load_dword v6, off, s[0:3], s32 offset:504
; CHECK-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:500
; CHECK-NEXT:    buffer_load_dword v4, off, s[0:3], s32 offset:496
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v7, off offset:30
; CHECK-NEXT:    global_store_byte v[12:13], v7, off offset:28
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v6, off offset:26
; CHECK-NEXT:    global_store_byte v[12:13], v6, off offset:24
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v5, off offset:22
; CHECK-NEXT:    global_store_byte v[12:13], v5, off offset:20
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v4, off offset:18
; CHECK-NEXT:    global_store_byte v[12:13], v4, off offset:16
; CHECK-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:512
; CHECK-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:516
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:520
; CHECK-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:524
; CHECK-NEXT:    s_clause 0x3
; CHECK-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:524
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:520
; CHECK-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:516
; CHECK-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:512
; CHECK-NEXT:    global_store_byte v[12:13], v100, off offset:255
; CHECK-NEXT:    v_lshrrev_b32_e32 v100, 24, v81
; CHECK-NEXT:    v_lshrrev_b32_e32 v81, 8, v81
; CHECK-NEXT:    global_store_byte v[12:13], v33, off offset:253
; CHECK-NEXT:    v_lshrrev_b32_e32 v33, 24, v80
; CHECK-NEXT:    v_lshrrev_b32_e32 v80, 8, v80
; CHECK-NEXT:    global_store_byte v[12:13], v101, off offset:251
; CHECK-NEXT:    v_lshrrev_b32_e32 v101, 24, v67
; CHECK-NEXT:    global_store_byte v[12:13], v81, off offset:221
; CHECK-NEXT:    v_lshrrev_b32_e32 v81, 24, v70
; CHECK-NEXT:    v_lshrrev_b32_e32 v70, 8, v70
; CHECK-NEXT:    v_lshrrev_b32_e32 v67, 8, v67
; CHECK-NEXT:    global_store_byte v[12:13], v32, off offset:249
; CHECK-NEXT:    v_lshrrev_b32_e32 v32, 24, v66
; CHECK-NEXT:    v_lshrrev_b32_e32 v66, 8, v66
; CHECK-NEXT:    global_store_byte v[12:13], v102, off offset:247
; CHECK-NEXT:    v_lshrrev_b32_e32 v102, 24, v98
; CHECK-NEXT:    v_lshrrev_b32_e32 v98, 8, v98
; CHECK-NEXT:    global_store_byte v[12:13], v27, off offset:245
; CHECK-NEXT:    v_lshrrev_b32_e32 v27, 24, v87
; CHECK-NEXT:    v_lshrrev_b32_e32 v87, 8, v87
; CHECK-NEXT:    global_store_byte v[12:13], v103, off offset:243
; CHECK-NEXT:    v_lshrrev_b32_e32 v103, 24, v86
; CHECK-NEXT:    v_lshrrev_b32_e32 v86, 8, v86
; CHECK-NEXT:    global_store_byte v[12:13], v26, off offset:241
; CHECK-NEXT:    v_lshrrev_b32_e32 v26, 24, v82
; CHECK-NEXT:    v_lshrrev_b32_e32 v82, 8, v82
; CHECK-NEXT:    global_store_byte v[12:13], v112, off offset:239
; CHECK-NEXT:    v_lshrrev_b32_e32 v112, 24, v99
; CHECK-NEXT:    v_lshrrev_b32_e32 v99, 8, v99
; CHECK-NEXT:    global_store_byte v[12:13], v53, off offset:237
; CHECK-NEXT:    v_lshrrev_b32_e32 v53, 24, v96
; CHECK-NEXT:    v_lshrrev_b32_e32 v96, 8, v96
; CHECK-NEXT:    global_store_byte v[12:13], v113, off offset:235
; CHECK-NEXT:    v_lshrrev_b32_e32 v113, 24, v83
; CHECK-NEXT:    v_lshrrev_b32_e32 v83, 8, v83
; CHECK-NEXT:    global_store_byte v[12:13], v52, off offset:233
; CHECK-NEXT:    v_lshrrev_b32_e32 v52, 24, v68
; CHECK-NEXT:    v_lshrrev_b32_e32 v68, 8, v68
; CHECK-NEXT:    global_store_byte v[12:13], v114, off offset:231
; CHECK-NEXT:    v_lshrrev_b32_e32 v114, 24, v97
; CHECK-NEXT:    v_lshrrev_b32_e32 v97, 8, v97
; CHECK-NEXT:    global_store_byte v[12:13], v51, off offset:229
; CHECK-NEXT:    v_lshrrev_b32_e32 v51, 24, v84
; CHECK-NEXT:    v_lshrrev_b32_e32 v84, 8, v84
; CHECK-NEXT:    global_store_byte v[12:13], v115, off offset:227
; CHECK-NEXT:    v_lshrrev_b32_e32 v115, 24, v69
; CHECK-NEXT:    v_lshrrev_b32_e32 v69, 8, v69
; CHECK-NEXT:    global_store_byte v[12:13], v50, off offset:225
; CHECK-NEXT:    v_lshrrev_b32_e32 v50, 24, v54
; CHECK-NEXT:    v_lshrrev_b32_e32 v54, 8, v54
; CHECK-NEXT:    global_store_byte v[12:13], v100, off offset:223
; CHECK-NEXT:    v_lshrrev_b32_e32 v100, 24, v85
; CHECK-NEXT:    v_lshrrev_b32_e32 v85, 8, v85
; CHECK-NEXT:    global_store_byte v[12:13], v33, off offset:219
; CHECK-NEXT:    v_lshrrev_b32_e32 v33, 24, v55
; CHECK-NEXT:    v_lshrrev_b32_e32 v55, 8, v55
; CHECK-NEXT:    global_store_byte v[12:13], v80, off offset:217
; CHECK-NEXT:    v_lshrrev_b32_e32 v80, 24, v38
; CHECK-NEXT:    v_lshrrev_b32_e32 v38, 8, v38
; CHECK-NEXT:    global_store_byte v[12:13], v101, off offset:215
; CHECK-NEXT:    v_lshrrev_b32_e32 v101, 24, v71
; CHECK-NEXT:    global_store_byte v[12:13], v70, off offset:153
; CHECK-NEXT:    v_lshrrev_b32_e32 v70, 24, v4
; CHECK-NEXT:    v_lshrrev_b32_e32 v4, 8, v4
; CHECK-NEXT:    v_lshrrev_b32_e32 v71, 8, v71
; CHECK-NEXT:    global_store_byte v[12:13], v67, off offset:213
; CHECK-NEXT:    v_lshrrev_b32_e32 v67, 24, v64
; CHECK-NEXT:    v_lshrrev_b32_e32 v64, 8, v64
; CHECK-NEXT:    global_store_byte v[12:13], v32, off offset:211
; CHECK-NEXT:    v_lshrrev_b32_e32 v32, 24, v39
; CHECK-NEXT:    v_lshrrev_b32_e32 v39, 8, v39
; CHECK-NEXT:    global_store_byte v[12:13], v66, off offset:209
; CHECK-NEXT:    v_lshrrev_b32_e32 v66, 24, v34
; CHECK-NEXT:    v_lshrrev_b32_e32 v34, 8, v34
; CHECK-NEXT:    global_store_byte v[12:13], v102, off offset:207
; CHECK-NEXT:    v_lshrrev_b32_e32 v102, 24, v65
; CHECK-NEXT:    v_lshrrev_b32_e32 v65, 8, v65
; CHECK-NEXT:    global_store_byte v[12:13], v98, off offset:205
; CHECK-NEXT:    v_lshrrev_b32_e32 v98, 24, v48
; CHECK-NEXT:    v_lshrrev_b32_e32 v48, 8, v48
; CHECK-NEXT:    global_store_byte v[12:13], v27, off offset:203
; CHECK-NEXT:    v_lshrrev_b32_e32 v27, 24, v35
; CHECK-NEXT:    v_lshrrev_b32_e32 v35, 8, v35
; CHECK-NEXT:    global_store_byte v[12:13], v87, off offset:201
; CHECK-NEXT:    v_lshrrev_b32_e32 v87, 24, v28
; CHECK-NEXT:    v_lshrrev_b32_e32 v28, 8, v28
; CHECK-NEXT:    global_store_byte v[12:13], v103, off offset:199
; CHECK-NEXT:    v_lshrrev_b32_e32 v103, 24, v49
; CHECK-NEXT:    v_lshrrev_b32_e32 v49, 8, v49
; CHECK-NEXT:    global_store_byte v[12:13], v86, off offset:197
; CHECK-NEXT:    v_lshrrev_b32_e32 v86, 24, v36
; CHECK-NEXT:    v_lshrrev_b32_e32 v36, 8, v36
; CHECK-NEXT:    global_store_byte v[12:13], v26, off offset:195
; CHECK-NEXT:    v_lshrrev_b32_e32 v26, 24, v29
; CHECK-NEXT:    v_lshrrev_b32_e32 v29, 8, v29
; CHECK-NEXT:    global_store_byte v[12:13], v82, off offset:193
; CHECK-NEXT:    v_lshrrev_b32_e32 v82, 24, v22
; CHECK-NEXT:    v_lshrrev_b32_e32 v22, 8, v22
; CHECK-NEXT:    global_store_byte v[12:13], v112, off offset:191
; CHECK-NEXT:    v_lshrrev_b32_e32 v112, 24, v37
; CHECK-NEXT:    v_lshrrev_b32_e32 v37, 8, v37
; CHECK-NEXT:    global_store_byte v[12:13], v99, off offset:189
; CHECK-NEXT:    v_lshrrev_b32_e32 v99, 24, v30
; CHECK-NEXT:    v_lshrrev_b32_e32 v30, 8, v30
; CHECK-NEXT:    global_store_byte v[12:13], v53, off offset:187
; CHECK-NEXT:    v_lshrrev_b32_e32 v53, 24, v23
; CHECK-NEXT:    v_lshrrev_b32_e32 v23, 8, v23
; CHECK-NEXT:    global_store_byte v[12:13], v96, off offset:185
; CHECK-NEXT:    v_lshrrev_b32_e32 v96, 24, v19
; CHECK-NEXT:    v_lshrrev_b32_e32 v19, 8, v19
; CHECK-NEXT:    global_store_byte v[12:13], v113, off offset:183
; CHECK-NEXT:    v_lshrrev_b32_e32 v113, 24, v31
; CHECK-NEXT:    v_lshrrev_b32_e32 v31, 8, v31
; CHECK-NEXT:    global_store_byte v[12:13], v83, off offset:181
; CHECK-NEXT:    v_lshrrev_b32_e32 v83, 24, v24
; CHECK-NEXT:    v_lshrrev_b32_e32 v24, 8, v24
; CHECK-NEXT:    global_store_byte v[12:13], v52, off offset:179
; CHECK-NEXT:    v_lshrrev_b32_e32 v52, 24, v20
; CHECK-NEXT:    v_lshrrev_b32_e32 v20, 8, v20
; CHECK-NEXT:    global_store_byte v[12:13], v68, off offset:177
; CHECK-NEXT:    v_lshrrev_b32_e32 v68, 24, v17
; CHECK-NEXT:    v_lshrrev_b32_e32 v17, 8, v17
; CHECK-NEXT:    global_store_byte v[12:13], v114, off offset:175
; CHECK-NEXT:    v_lshrrev_b32_e32 v114, 24, v25
; CHECK-NEXT:    v_lshrrev_b32_e32 v25, 8, v25
; CHECK-NEXT:    global_store_byte v[12:13], v97, off offset:173
; CHECK-NEXT:    v_lshrrev_b32_e32 v97, 24, v21
; CHECK-NEXT:    v_lshrrev_b32_e32 v21, 8, v21
; CHECK-NEXT:    global_store_byte v[12:13], v51, off offset:171
; CHECK-NEXT:    v_lshrrev_b32_e32 v51, 24, v18
; CHECK-NEXT:    v_lshrrev_b32_e32 v18, 8, v18
; CHECK-NEXT:    global_store_byte v[12:13], v84, off offset:169
; CHECK-NEXT:    v_lshrrev_b32_e32 v84, 24, v16
; CHECK-NEXT:    v_lshrrev_b32_e32 v16, 8, v16
; CHECK-NEXT:    global_store_byte v[12:13], v115, off offset:167
; CHECK-NEXT:    v_lshrrev_b32_e32 v115, 24, v11
; CHECK-NEXT:    v_lshrrev_b32_e32 v11, 8, v11
; CHECK-NEXT:    global_store_byte v[12:13], v69, off offset:165
; CHECK-NEXT:    v_lshrrev_b32_e32 v69, 24, v10
; CHECK-NEXT:    v_lshrrev_b32_e32 v10, 8, v10
; CHECK-NEXT:    global_store_byte v[12:13], v50, off offset:163
; CHECK-NEXT:    v_lshrrev_b32_e32 v50, 24, v9
; CHECK-NEXT:    v_lshrrev_b32_e32 v9, 8, v9
; CHECK-NEXT:    global_store_byte v[12:13], v54, off offset:161
; CHECK-NEXT:    v_lshrrev_b32_e32 v54, 24, v8
; CHECK-NEXT:    v_lshrrev_b32_e32 v8, 8, v8
; CHECK-NEXT:    global_store_byte v[12:13], v100, off offset:159
; CHECK-NEXT:    v_lshrrev_b32_e32 v100, 24, v7
; CHECK-NEXT:    v_lshrrev_b32_e32 v7, 8, v7
; CHECK-NEXT:    global_store_byte v[12:13], v85, off offset:157
; CHECK-NEXT:    v_lshrrev_b32_e32 v85, 24, v6
; CHECK-NEXT:    v_lshrrev_b32_e32 v6, 8, v6
; CHECK-NEXT:    global_store_byte v[12:13], v81, off offset:155
; CHECK-NEXT:    v_lshrrev_b32_e32 v81, 24, v5
; CHECK-NEXT:    v_lshrrev_b32_e32 v5, 8, v5
; CHECK-NEXT:    global_store_byte v[12:13], v33, off offset:151
; CHECK-NEXT:    global_store_byte v[12:13], v55, off offset:149
; CHECK-NEXT:    global_store_byte v[12:13], v80, off offset:147
; CHECK-NEXT:    global_store_byte v[12:13], v38, off offset:145
; CHECK-NEXT:    global_store_byte v[12:13], v101, off offset:143
; CHECK-NEXT:    global_store_byte v[12:13], v71, off offset:141
; CHECK-NEXT:    global_store_byte v[12:13], v67, off offset:139
; CHECK-NEXT:    global_store_byte v[12:13], v64, off offset:137
; CHECK-NEXT:    global_store_byte v[12:13], v32, off offset:135
; CHECK-NEXT:    global_store_byte v[12:13], v39, off offset:133
; CHECK-NEXT:    global_store_byte v[12:13], v66, off offset:131
; CHECK-NEXT:    global_store_byte v[12:13], v34, off offset:129
; CHECK-NEXT:    global_store_byte v[12:13], v102, off offset:127
; CHECK-NEXT:    global_store_byte v[12:13], v65, off offset:125
; CHECK-NEXT:    global_store_byte v[12:13], v98, off offset:123
; CHECK-NEXT:    global_store_byte v[12:13], v48, off offset:121
; CHECK-NEXT:    global_store_byte v[12:13], v27, off offset:119
; CHECK-NEXT:    global_store_byte v[12:13], v35, off offset:117
; CHECK-NEXT:    global_store_byte v[12:13], v87, off offset:115
; CHECK-NEXT:    global_store_byte v[12:13], v28, off offset:113
; CHECK-NEXT:    global_store_byte v[12:13], v103, off offset:111
; CHECK-NEXT:    global_store_byte v[12:13], v49, off offset:109
; CHECK-NEXT:    global_store_byte v[12:13], v86, off offset:107
; CHECK-NEXT:    global_store_byte v[12:13], v36, off offset:105
; CHECK-NEXT:    global_store_byte v[12:13], v26, off offset:103
; CHECK-NEXT:    global_store_byte v[12:13], v29, off offset:101
; CHECK-NEXT:    global_store_byte v[12:13], v82, off offset:99
; CHECK-NEXT:    global_store_byte v[12:13], v22, off offset:97
; CHECK-NEXT:    global_store_byte v[12:13], v112, off offset:95
; CHECK-NEXT:    global_store_byte v[12:13], v37, off offset:93
; CHECK-NEXT:    global_store_byte v[12:13], v99, off offset:91
; CHECK-NEXT:    global_store_byte v[12:13], v30, off offset:89
; CHECK-NEXT:    global_store_byte v[12:13], v53, off offset:87
; CHECK-NEXT:    global_store_byte v[12:13], v23, off offset:85
; CHECK-NEXT:    global_store_byte v[12:13], v96, off offset:83
; CHECK-NEXT:    global_store_byte v[12:13], v19, off offset:81
; CHECK-NEXT:    global_store_byte v[12:13], v113, off offset:79
; CHECK-NEXT:    global_store_byte v[12:13], v31, off offset:77
; CHECK-NEXT:    global_store_byte v[12:13], v83, off offset:75
; CHECK-NEXT:    global_store_byte v[12:13], v24, off offset:73
; CHECK-NEXT:    global_store_byte v[12:13], v52, off offset:71
; CHECK-NEXT:    global_store_byte v[12:13], v20, off offset:69
; CHECK-NEXT:    global_store_byte v[12:13], v68, off offset:67
; CHECK-NEXT:    global_store_byte v[12:13], v17, off offset:65
; CHECK-NEXT:    global_store_byte v[12:13], v114, off offset:63
; CHECK-NEXT:    global_store_byte v[12:13], v25, off offset:61
; CHECK-NEXT:    global_store_byte v[12:13], v97, off offset:59
; CHECK-NEXT:    global_store_byte v[12:13], v21, off offset:57
; CHECK-NEXT:    global_store_byte v[12:13], v51, off offset:55
; CHECK-NEXT:    global_store_byte v[12:13], v18, off offset:53
; CHECK-NEXT:    global_store_byte v[12:13], v84, off offset:51
; CHECK-NEXT:    global_store_byte v[12:13], v16, off offset:49
; CHECK-NEXT:    global_store_byte v[12:13], v115, off offset:43
; CHECK-NEXT:    global_store_byte v[12:13], v11, off offset:41
; CHECK-NEXT:    global_store_byte v[12:13], v69, off offset:47
; CHECK-NEXT:    global_store_byte v[12:13], v10, off offset:45
; CHECK-NEXT:    global_store_byte v[12:13], v50, off offset:35
; CHECK-NEXT:    global_store_byte v[12:13], v9, off offset:33
; CHECK-NEXT:    global_store_byte v[12:13], v54, off offset:39
; CHECK-NEXT:    global_store_byte v[12:13], v8, off offset:37
; CHECK-NEXT:    global_store_byte v[12:13], v100, off offset:31
; CHECK-NEXT:    global_store_byte v[12:13], v7, off offset:29
; CHECK-NEXT:    global_store_byte v[12:13], v85, off offset:27
; CHECK-NEXT:    global_store_byte v[12:13], v6, off offset:25
; CHECK-NEXT:    global_store_byte v[12:13], v81, off offset:23
; CHECK-NEXT:    global_store_byte v[12:13], v5, off offset:21
; CHECK-NEXT:    global_store_byte v[12:13], v70, off offset:19
; CHECK-NEXT:    global_store_byte v[12:13], v4, off offset:17
; CHECK-NEXT:    s_waitcnt vmcnt(3)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v3, off offset:14
; CHECK-NEXT:    global_store_byte v[12:13], v3, off offset:12
; CHECK-NEXT:    s_waitcnt vmcnt(2)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v2, off offset:10
; CHECK-NEXT:    global_store_byte v[12:13], v2, off offset:8
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v1, off offset:6
; CHECK-NEXT:    global_store_byte v[12:13], v1, off offset:4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    global_store_byte_d16_hi v[12:13], v0, off offset:2
; CHECK-NEXT:    global_store_byte v[12:13], v0, off
; CHECK-NEXT:    v_lshrrev_b32_e32 v4, 24, v3
; CHECK-NEXT:    v_lshrrev_b32_e32 v3, 8, v3
; CHECK-NEXT:    v_lshrrev_b32_e32 v5, 24, v2
; CHECK-NEXT:    v_lshrrev_b32_e32 v2, 8, v2
; CHECK-NEXT:    v_lshrrev_b32_e32 v6, 24, v1
; CHECK-NEXT:    v_lshrrev_b32_e32 v1, 8, v1
; CHECK-NEXT:    v_lshrrev_b32_e32 v7, 24, v0
; CHECK-NEXT:    v_lshrrev_b32_e32 v0, 8, v0
; CHECK-NEXT:    global_store_byte v[12:13], v4, off offset:15
; CHECK-NEXT:    global_store_byte v[12:13], v3, off offset:13
; CHECK-NEXT:    global_store_byte v[12:13], v5, off offset:11
; CHECK-NEXT:    global_store_byte v[12:13], v2, off offset:9
; CHECK-NEXT:    global_store_byte v[12:13], v6, off offset:7
; CHECK-NEXT:    global_store_byte v[12:13], v1, off offset:5
; CHECK-NEXT:    global_store_byte v[12:13], v7, off offset:3
; CHECK-NEXT:    global_store_byte v[12:13], v0, off offset:1
; CHECK-NEXT:    v_add_co_u32 v12, vcc_lo, 0xffffff00, v12
; CHECK-NEXT:    v_add_co_ci_u32_e64 v13, null, -1, v13, vcc_lo
; CHECK-NEXT:    s_cbranch_scc0 .LBB0_5
; CHECK-NEXT:  .LBB0_6: ; %Flow18
; CHECK-NEXT:    s_or_b32 exec_lo, exec_lo, s6
; CHECK-NEXT:    s_clause 0x9 ; 40-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v57, off, s[0:3], s32
; CHECK-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:4
; CHECK-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:8
; CHECK-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:12
; CHECK-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:16
; CHECK-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:20
; CHECK-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:24
; CHECK-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:28
; CHECK-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:32
; CHECK-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:36
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  tail call void @llvm.memmove.p1.p1.i64(ptr addrspace(1) noundef nonnull align 1 %dst, ptr addrspace(1) noundef nonnull align 1 %src, i64 2048, i1 false)
  ret void
}


declare void @llvm.memmove.p1.p1.i64(ptr addrspace(1) nocapture writeonly, ptr addrspace(1) nocapture readonly, i64, i1 immarg) #2

attributes #1 = { nounwind }
attributes #2 = { nocallback nofree nounwind willreturn memory(argmem: readwrite) }
