; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5

; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1030 -mattr=-unaligned-access-mode %s -o - | FileCheck %s

; For checking that LowerMemIntrinsics lowers memcpy and memmove with large
; constant copy-sizes into loops with multiple load/store pairs.

define void @memcpy_p5_p5_sz2048(ptr addrspace(5) align 1 %dst, ptr addrspace(5) align 1 readonly %src) #1 {
;
; CHECK-LABEL: memcpy_p5_p5_sz2048:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:188 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:184 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:180 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:176 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:172 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:168 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:164 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:160 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:156 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:152 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:148 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:144 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:140 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:136 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:132 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v63, off, s[0:3], s32 offset:128 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v72, off, s[0:3], s32 offset:124 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v73, off, s[0:3], s32 offset:120 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v74, off, s[0:3], s32 offset:116 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v75, off, s[0:3], s32 offset:112 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v76, off, s[0:3], s32 offset:108 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v77, off, s[0:3], s32 offset:104 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v78, off, s[0:3], s32 offset:100 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v79, off, s[0:3], s32 offset:96 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v88, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v89, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v90, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v91, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v92, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v93, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v94, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v95, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v104, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v105, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v106, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v107, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v108, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v109, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v110, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v111, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v120, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v121, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v122, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v123, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v124, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v125, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v126, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v127, off, s[0:3], s32 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:  .LBB0_1: ; %static-memcpy-expansion-main-body
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen
; CHECK-NEXT:    s_add_u32 s4, s4, 0x100
; CHECK-NEXT:    s_addc_u32 s5, s5, 0
; CHECK-NEXT:    v_cmp_gt_u64_e64 s6, 0x800, s[4:5]
; CHECK-NEXT:    s_and_b32 vcc_lo, exec_lo, s6
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:192 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:1
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:196 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:2
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:200 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:3
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:204 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:4
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:208 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:5
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:212 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:6
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:216 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:7
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:220 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:8
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:224 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:9
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:228 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:10
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:232 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:11
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:236 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:12
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:240 ; 4-byte Folded Spill
; CHECK-NEXT:    s_clause 0x34
; CHECK-NEXT:    buffer_load_ubyte v116, v1, s[0:3], 0 offen offset:255
; CHECK-NEXT:    buffer_load_ubyte v117, v1, s[0:3], 0 offen offset:254
; CHECK-NEXT:    buffer_load_ubyte v118, v1, s[0:3], 0 offen offset:253
; CHECK-NEXT:    buffer_load_ubyte v119, v1, s[0:3], 0 offen offset:252
; CHECK-NEXT:    buffer_load_ubyte v40, v1, s[0:3], 0 offen offset:251
; CHECK-NEXT:    buffer_load_ubyte v41, v1, s[0:3], 0 offen offset:250
; CHECK-NEXT:    buffer_load_ubyte v42, v1, s[0:3], 0 offen offset:249
; CHECK-NEXT:    buffer_load_ubyte v43, v1, s[0:3], 0 offen offset:248
; CHECK-NEXT:    buffer_load_ubyte v44, v1, s[0:3], 0 offen offset:247
; CHECK-NEXT:    buffer_load_ubyte v45, v1, s[0:3], 0 offen offset:246
; CHECK-NEXT:    buffer_load_ubyte v46, v1, s[0:3], 0 offen offset:245
; CHECK-NEXT:    buffer_load_ubyte v47, v1, s[0:3], 0 offen offset:244
; CHECK-NEXT:    buffer_load_ubyte v56, v1, s[0:3], 0 offen offset:243
; CHECK-NEXT:    buffer_load_ubyte v57, v1, s[0:3], 0 offen offset:242
; CHECK-NEXT:    buffer_load_ubyte v58, v1, s[0:3], 0 offen offset:241
; CHECK-NEXT:    buffer_load_ubyte v59, v1, s[0:3], 0 offen offset:240
; CHECK-NEXT:    buffer_load_ubyte v60, v1, s[0:3], 0 offen offset:239
; CHECK-NEXT:    buffer_load_ubyte v61, v1, s[0:3], 0 offen offset:238
; CHECK-NEXT:    buffer_load_ubyte v62, v1, s[0:3], 0 offen offset:237
; CHECK-NEXT:    buffer_load_ubyte v63, v1, s[0:3], 0 offen offset:236
; CHECK-NEXT:    buffer_load_ubyte v72, v1, s[0:3], 0 offen offset:235
; CHECK-NEXT:    buffer_load_ubyte v73, v1, s[0:3], 0 offen offset:234
; CHECK-NEXT:    buffer_load_ubyte v74, v1, s[0:3], 0 offen offset:233
; CHECK-NEXT:    buffer_load_ubyte v75, v1, s[0:3], 0 offen offset:232
; CHECK-NEXT:    buffer_load_ubyte v76, v1, s[0:3], 0 offen offset:231
; CHECK-NEXT:    buffer_load_ubyte v77, v1, s[0:3], 0 offen offset:230
; CHECK-NEXT:    buffer_load_ubyte v78, v1, s[0:3], 0 offen offset:229
; CHECK-NEXT:    buffer_load_ubyte v79, v1, s[0:3], 0 offen offset:228
; CHECK-NEXT:    buffer_load_ubyte v88, v1, s[0:3], 0 offen offset:227
; CHECK-NEXT:    buffer_load_ubyte v89, v1, s[0:3], 0 offen offset:226
; CHECK-NEXT:    buffer_load_ubyte v90, v1, s[0:3], 0 offen offset:225
; CHECK-NEXT:    buffer_load_ubyte v91, v1, s[0:3], 0 offen offset:224
; CHECK-NEXT:    buffer_load_ubyte v92, v1, s[0:3], 0 offen offset:223
; CHECK-NEXT:    buffer_load_ubyte v93, v1, s[0:3], 0 offen offset:222
; CHECK-NEXT:    buffer_load_ubyte v94, v1, s[0:3], 0 offen offset:221
; CHECK-NEXT:    buffer_load_ubyte v95, v1, s[0:3], 0 offen offset:220
; CHECK-NEXT:    buffer_load_ubyte v104, v1, s[0:3], 0 offen offset:219
; CHECK-NEXT:    buffer_load_ubyte v105, v1, s[0:3], 0 offen offset:218
; CHECK-NEXT:    buffer_load_ubyte v106, v1, s[0:3], 0 offen offset:217
; CHECK-NEXT:    buffer_load_ubyte v107, v1, s[0:3], 0 offen offset:216
; CHECK-NEXT:    buffer_load_ubyte v108, v1, s[0:3], 0 offen offset:215
; CHECK-NEXT:    buffer_load_ubyte v109, v1, s[0:3], 0 offen offset:214
; CHECK-NEXT:    buffer_load_ubyte v110, v1, s[0:3], 0 offen offset:213
; CHECK-NEXT:    buffer_load_ubyte v111, v1, s[0:3], 0 offen offset:212
; CHECK-NEXT:    buffer_load_ubyte v120, v1, s[0:3], 0 offen offset:211
; CHECK-NEXT:    buffer_load_ubyte v121, v1, s[0:3], 0 offen offset:210
; CHECK-NEXT:    buffer_load_ubyte v122, v1, s[0:3], 0 offen offset:209
; CHECK-NEXT:    buffer_load_ubyte v123, v1, s[0:3], 0 offen offset:208
; CHECK-NEXT:    buffer_load_ubyte v124, v1, s[0:3], 0 offen offset:207
; CHECK-NEXT:    buffer_load_ubyte v125, v1, s[0:3], 0 offen offset:206
; CHECK-NEXT:    buffer_load_ubyte v126, v1, s[0:3], 0 offen offset:205
; CHECK-NEXT:    buffer_load_ubyte v127, v1, s[0:3], 0 offen offset:204
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:203
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:712 ; 4-byte Folded Spill
; CHECK-NEXT:    s_clause 0x3e
; CHECK-NEXT:    buffer_load_ubyte v3, v1, s[0:3], 0 offen offset:202
; CHECK-NEXT:    buffer_load_ubyte v4, v1, s[0:3], 0 offen offset:201
; CHECK-NEXT:    buffer_load_ubyte v5, v1, s[0:3], 0 offen offset:200
; CHECK-NEXT:    buffer_load_ubyte v6, v1, s[0:3], 0 offen offset:199
; CHECK-NEXT:    buffer_load_ubyte v7, v1, s[0:3], 0 offen offset:198
; CHECK-NEXT:    buffer_load_ubyte v8, v1, s[0:3], 0 offen offset:197
; CHECK-NEXT:    buffer_load_ubyte v9, v1, s[0:3], 0 offen offset:196
; CHECK-NEXT:    buffer_load_ubyte v10, v1, s[0:3], 0 offen offset:195
; CHECK-NEXT:    buffer_load_ubyte v11, v1, s[0:3], 0 offen offset:194
; CHECK-NEXT:    buffer_load_ubyte v12, v1, s[0:3], 0 offen offset:193
; CHECK-NEXT:    buffer_load_ubyte v13, v1, s[0:3], 0 offen offset:192
; CHECK-NEXT:    buffer_load_ubyte v14, v1, s[0:3], 0 offen offset:191
; CHECK-NEXT:    buffer_load_ubyte v15, v1, s[0:3], 0 offen offset:190
; CHECK-NEXT:    buffer_load_ubyte v16, v1, s[0:3], 0 offen offset:189
; CHECK-NEXT:    buffer_load_ubyte v17, v1, s[0:3], 0 offen offset:188
; CHECK-NEXT:    buffer_load_ubyte v18, v1, s[0:3], 0 offen offset:187
; CHECK-NEXT:    buffer_load_ubyte v19, v1, s[0:3], 0 offen offset:186
; CHECK-NEXT:    buffer_load_ubyte v20, v1, s[0:3], 0 offen offset:185
; CHECK-NEXT:    buffer_load_ubyte v21, v1, s[0:3], 0 offen offset:184
; CHECK-NEXT:    buffer_load_ubyte v22, v1, s[0:3], 0 offen offset:183
; CHECK-NEXT:    buffer_load_ubyte v23, v1, s[0:3], 0 offen offset:182
; CHECK-NEXT:    buffer_load_ubyte v24, v1, s[0:3], 0 offen offset:181
; CHECK-NEXT:    buffer_load_ubyte v25, v1, s[0:3], 0 offen offset:180
; CHECK-NEXT:    buffer_load_ubyte v26, v1, s[0:3], 0 offen offset:179
; CHECK-NEXT:    buffer_load_ubyte v27, v1, s[0:3], 0 offen offset:178
; CHECK-NEXT:    buffer_load_ubyte v28, v1, s[0:3], 0 offen offset:177
; CHECK-NEXT:    buffer_load_ubyte v29, v1, s[0:3], 0 offen offset:176
; CHECK-NEXT:    buffer_load_ubyte v30, v1, s[0:3], 0 offen offset:175
; CHECK-NEXT:    buffer_load_ubyte v31, v1, s[0:3], 0 offen offset:174
; CHECK-NEXT:    buffer_load_ubyte v32, v1, s[0:3], 0 offen offset:173
; CHECK-NEXT:    buffer_load_ubyte v33, v1, s[0:3], 0 offen offset:172
; CHECK-NEXT:    buffer_load_ubyte v34, v1, s[0:3], 0 offen offset:171
; CHECK-NEXT:    buffer_load_ubyte v35, v1, s[0:3], 0 offen offset:170
; CHECK-NEXT:    buffer_load_ubyte v36, v1, s[0:3], 0 offen offset:169
; CHECK-NEXT:    buffer_load_ubyte v37, v1, s[0:3], 0 offen offset:168
; CHECK-NEXT:    buffer_load_ubyte v38, v1, s[0:3], 0 offen offset:167
; CHECK-NEXT:    buffer_load_ubyte v39, v1, s[0:3], 0 offen offset:166
; CHECK-NEXT:    buffer_load_ubyte v48, v1, s[0:3], 0 offen offset:165
; CHECK-NEXT:    buffer_load_ubyte v49, v1, s[0:3], 0 offen offset:164
; CHECK-NEXT:    buffer_load_ubyte v50, v1, s[0:3], 0 offen offset:163
; CHECK-NEXT:    buffer_load_ubyte v51, v1, s[0:3], 0 offen offset:162
; CHECK-NEXT:    buffer_load_ubyte v52, v1, s[0:3], 0 offen offset:161
; CHECK-NEXT:    buffer_load_ubyte v53, v1, s[0:3], 0 offen offset:160
; CHECK-NEXT:    buffer_load_ubyte v54, v1, s[0:3], 0 offen offset:159
; CHECK-NEXT:    buffer_load_ubyte v55, v1, s[0:3], 0 offen offset:158
; CHECK-NEXT:    buffer_load_ubyte v64, v1, s[0:3], 0 offen offset:157
; CHECK-NEXT:    buffer_load_ubyte v65, v1, s[0:3], 0 offen offset:156
; CHECK-NEXT:    buffer_load_ubyte v66, v1, s[0:3], 0 offen offset:155
; CHECK-NEXT:    buffer_load_ubyte v67, v1, s[0:3], 0 offen offset:154
; CHECK-NEXT:    buffer_load_ubyte v68, v1, s[0:3], 0 offen offset:153
; CHECK-NEXT:    buffer_load_ubyte v69, v1, s[0:3], 0 offen offset:152
; CHECK-NEXT:    buffer_load_ubyte v70, v1, s[0:3], 0 offen offset:151
; CHECK-NEXT:    buffer_load_ubyte v71, v1, s[0:3], 0 offen offset:150
; CHECK-NEXT:    buffer_load_ubyte v80, v1, s[0:3], 0 offen offset:149
; CHECK-NEXT:    buffer_load_ubyte v81, v1, s[0:3], 0 offen offset:148
; CHECK-NEXT:    buffer_load_ubyte v82, v1, s[0:3], 0 offen offset:147
; CHECK-NEXT:    buffer_load_ubyte v83, v1, s[0:3], 0 offen offset:146
; CHECK-NEXT:    buffer_load_ubyte v84, v1, s[0:3], 0 offen offset:145
; CHECK-NEXT:    buffer_load_ubyte v85, v1, s[0:3], 0 offen offset:144
; CHECK-NEXT:    buffer_load_ubyte v86, v1, s[0:3], 0 offen offset:143
; CHECK-NEXT:    buffer_load_ubyte v87, v1, s[0:3], 0 offen offset:142
; CHECK-NEXT:    buffer_load_ubyte v96, v1, s[0:3], 0 offen offset:141
; CHECK-NEXT:    buffer_load_ubyte v97, v1, s[0:3], 0 offen offset:140
; CHECK-NEXT:    s_clause 0xa
; CHECK-NEXT:    buffer_load_ubyte v98, v1, s[0:3], 0 offen offset:139
; CHECK-NEXT:    buffer_load_ubyte v99, v1, s[0:3], 0 offen offset:138
; CHECK-NEXT:    buffer_load_ubyte v100, v1, s[0:3], 0 offen offset:137
; CHECK-NEXT:    buffer_load_ubyte v101, v1, s[0:3], 0 offen offset:136
; CHECK-NEXT:    buffer_load_ubyte v102, v1, s[0:3], 0 offen offset:135
; CHECK-NEXT:    buffer_load_ubyte v103, v1, s[0:3], 0 offen offset:134
; CHECK-NEXT:    buffer_load_ubyte v112, v1, s[0:3], 0 offen offset:133
; CHECK-NEXT:    buffer_load_ubyte v113, v1, s[0:3], 0 offen offset:132
; CHECK-NEXT:    buffer_load_ubyte v114, v1, s[0:3], 0 offen offset:131
; CHECK-NEXT:    buffer_load_ubyte v115, v1, s[0:3], 0 offen offset:130
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:129
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:708 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:128
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:704 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:127
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:700 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:126
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:696 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:125
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:692 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:124
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:688 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:123
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:684 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:122
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:680 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:121
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:676 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:120
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:672 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:119
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:668 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:118
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:664 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:117
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:660 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:116
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:656 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:115
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:652 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:114
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:648 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:113
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:644 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:112
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:640 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:111
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:636 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:110
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:632 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:109
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:628 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:108
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:624 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:107
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:620 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:106
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:616 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:105
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:612 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:104
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:608 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:103
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:604 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:102
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:600 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:101
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:596 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:100
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:592 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:99
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:588 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:98
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:584 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:97
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:580 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:96
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:576 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:95
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:572 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:94
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:568 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:93
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:564 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:92
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:560 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:91
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:556 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:90
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:552 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:89
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:548 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:88
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:544 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:87
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:540 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:86
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:536 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:85
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:532 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:84
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:528 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:83
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:524 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:82
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:520 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:81
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:516 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:80
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:512 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:79
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:508 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:78
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:504 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:77
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:500 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:76
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:496 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:75
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:492 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:74
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:488 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:73
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:484 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:72
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:480 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:71
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:476 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:70
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:472 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:69
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:468 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:68
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:464 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:67
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:460 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:66
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:456 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:65
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:452 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:64
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:448 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:63
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:444 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:62
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:440 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:61
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:436 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:60
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:432 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:59
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:428 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:58
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:424 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:57
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:420 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:56
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:416 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:55
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:412 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:54
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:408 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:53
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:404 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:52
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:400 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:51
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:396 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:50
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:392 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:49
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:388 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:48
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:384 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:47
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:380 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:46
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:376 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:45
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:372 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:44
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:368 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:43
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:364 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:42
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:360 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:41
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:356 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:40
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:352 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:39
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:348 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:38
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:344 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:37
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:340 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:36
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:336 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:35
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:332 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:34
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:328 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:33
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:324 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:32
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:320 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:31
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:316 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:30
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:312 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:29
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:308 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:28
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:304 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:27
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:300 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:26
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:296 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:25
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:292 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:24
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:288 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:23
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:284 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:22
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:280 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:21
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:276 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:20
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:272 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:19
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:268 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:18
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:264 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:17
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:260 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:16
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:256 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:15
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:252 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:14
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:248 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_load_ubyte v2, v1, s[0:3], 0 offen offset:13
; CHECK-NEXT:    v_add_nc_u32_e32 v1, 0x100, v1
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:244 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_byte v116, v0, s[0:3], 0 offen offset:255
; CHECK-NEXT:    buffer_store_byte v117, v0, s[0:3], 0 offen offset:254
; CHECK-NEXT:    buffer_store_byte v118, v0, s[0:3], 0 offen offset:253
; CHECK-NEXT:    buffer_store_byte v119, v0, s[0:3], 0 offen offset:252
; CHECK-NEXT:    buffer_store_byte v40, v0, s[0:3], 0 offen offset:251
; CHECK-NEXT:    buffer_store_byte v41, v0, s[0:3], 0 offen offset:250
; CHECK-NEXT:    buffer_store_byte v42, v0, s[0:3], 0 offen offset:249
; CHECK-NEXT:    buffer_store_byte v43, v0, s[0:3], 0 offen offset:248
; CHECK-NEXT:    buffer_store_byte v44, v0, s[0:3], 0 offen offset:247
; CHECK-NEXT:    buffer_store_byte v45, v0, s[0:3], 0 offen offset:246
; CHECK-NEXT:    buffer_store_byte v46, v0, s[0:3], 0 offen offset:245
; CHECK-NEXT:    buffer_store_byte v47, v0, s[0:3], 0 offen offset:244
; CHECK-NEXT:    buffer_store_byte v56, v0, s[0:3], 0 offen offset:243
; CHECK-NEXT:    buffer_store_byte v57, v0, s[0:3], 0 offen offset:242
; CHECK-NEXT:    buffer_store_byte v58, v0, s[0:3], 0 offen offset:241
; CHECK-NEXT:    buffer_store_byte v59, v0, s[0:3], 0 offen offset:240
; CHECK-NEXT:    buffer_store_byte v60, v0, s[0:3], 0 offen offset:239
; CHECK-NEXT:    buffer_store_byte v61, v0, s[0:3], 0 offen offset:238
; CHECK-NEXT:    buffer_store_byte v62, v0, s[0:3], 0 offen offset:237
; CHECK-NEXT:    buffer_store_byte v63, v0, s[0:3], 0 offen offset:236
; CHECK-NEXT:    buffer_store_byte v72, v0, s[0:3], 0 offen offset:235
; CHECK-NEXT:    buffer_store_byte v73, v0, s[0:3], 0 offen offset:234
; CHECK-NEXT:    buffer_store_byte v74, v0, s[0:3], 0 offen offset:233
; CHECK-NEXT:    buffer_store_byte v75, v0, s[0:3], 0 offen offset:232
; CHECK-NEXT:    buffer_store_byte v76, v0, s[0:3], 0 offen offset:231
; CHECK-NEXT:    buffer_store_byte v77, v0, s[0:3], 0 offen offset:230
; CHECK-NEXT:    buffer_store_byte v78, v0, s[0:3], 0 offen offset:229
; CHECK-NEXT:    buffer_store_byte v79, v0, s[0:3], 0 offen offset:228
; CHECK-NEXT:    buffer_store_byte v88, v0, s[0:3], 0 offen offset:227
; CHECK-NEXT:    buffer_store_byte v89, v0, s[0:3], 0 offen offset:226
; CHECK-NEXT:    buffer_store_byte v90, v0, s[0:3], 0 offen offset:225
; CHECK-NEXT:    buffer_store_byte v91, v0, s[0:3], 0 offen offset:224
; CHECK-NEXT:    buffer_store_byte v92, v0, s[0:3], 0 offen offset:223
; CHECK-NEXT:    buffer_store_byte v93, v0, s[0:3], 0 offen offset:222
; CHECK-NEXT:    buffer_store_byte v94, v0, s[0:3], 0 offen offset:221
; CHECK-NEXT:    buffer_store_byte v95, v0, s[0:3], 0 offen offset:220
; CHECK-NEXT:    buffer_store_byte v104, v0, s[0:3], 0 offen offset:219
; CHECK-NEXT:    buffer_store_byte v105, v0, s[0:3], 0 offen offset:218
; CHECK-NEXT:    buffer_store_byte v106, v0, s[0:3], 0 offen offset:217
; CHECK-NEXT:    buffer_store_byte v107, v0, s[0:3], 0 offen offset:216
; CHECK-NEXT:    buffer_store_byte v108, v0, s[0:3], 0 offen offset:215
; CHECK-NEXT:    buffer_store_byte v109, v0, s[0:3], 0 offen offset:214
; CHECK-NEXT:    buffer_store_byte v110, v0, s[0:3], 0 offen offset:213
; CHECK-NEXT:    buffer_store_byte v111, v0, s[0:3], 0 offen offset:212
; CHECK-NEXT:    buffer_store_byte v120, v0, s[0:3], 0 offen offset:211
; CHECK-NEXT:    buffer_store_byte v121, v0, s[0:3], 0 offen offset:210
; CHECK-NEXT:    buffer_store_byte v122, v0, s[0:3], 0 offen offset:209
; CHECK-NEXT:    buffer_store_byte v123, v0, s[0:3], 0 offen offset:208
; CHECK-NEXT:    buffer_store_byte v124, v0, s[0:3], 0 offen offset:207
; CHECK-NEXT:    buffer_store_byte v125, v0, s[0:3], 0 offen offset:206
; CHECK-NEXT:    buffer_store_byte v126, v0, s[0:3], 0 offen offset:205
; CHECK-NEXT:    buffer_store_byte v127, v0, s[0:3], 0 offen offset:204
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:712 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:203
; CHECK-NEXT:    buffer_store_byte v3, v0, s[0:3], 0 offen offset:202
; CHECK-NEXT:    buffer_store_byte v4, v0, s[0:3], 0 offen offset:201
; CHECK-NEXT:    buffer_store_byte v5, v0, s[0:3], 0 offen offset:200
; CHECK-NEXT:    buffer_store_byte v6, v0, s[0:3], 0 offen offset:199
; CHECK-NEXT:    buffer_store_byte v7, v0, s[0:3], 0 offen offset:198
; CHECK-NEXT:    buffer_store_byte v8, v0, s[0:3], 0 offen offset:197
; CHECK-NEXT:    buffer_store_byte v9, v0, s[0:3], 0 offen offset:196
; CHECK-NEXT:    buffer_store_byte v10, v0, s[0:3], 0 offen offset:195
; CHECK-NEXT:    buffer_store_byte v11, v0, s[0:3], 0 offen offset:194
; CHECK-NEXT:    buffer_store_byte v12, v0, s[0:3], 0 offen offset:193
; CHECK-NEXT:    buffer_store_byte v13, v0, s[0:3], 0 offen offset:192
; CHECK-NEXT:    buffer_store_byte v14, v0, s[0:3], 0 offen offset:191
; CHECK-NEXT:    buffer_store_byte v15, v0, s[0:3], 0 offen offset:190
; CHECK-NEXT:    buffer_store_byte v16, v0, s[0:3], 0 offen offset:189
; CHECK-NEXT:    buffer_store_byte v17, v0, s[0:3], 0 offen offset:188
; CHECK-NEXT:    buffer_store_byte v18, v0, s[0:3], 0 offen offset:187
; CHECK-NEXT:    buffer_store_byte v19, v0, s[0:3], 0 offen offset:186
; CHECK-NEXT:    buffer_store_byte v20, v0, s[0:3], 0 offen offset:185
; CHECK-NEXT:    buffer_store_byte v21, v0, s[0:3], 0 offen offset:184
; CHECK-NEXT:    buffer_store_byte v22, v0, s[0:3], 0 offen offset:183
; CHECK-NEXT:    buffer_store_byte v23, v0, s[0:3], 0 offen offset:182
; CHECK-NEXT:    buffer_store_byte v24, v0, s[0:3], 0 offen offset:181
; CHECK-NEXT:    buffer_store_byte v25, v0, s[0:3], 0 offen offset:180
; CHECK-NEXT:    buffer_store_byte v26, v0, s[0:3], 0 offen offset:179
; CHECK-NEXT:    buffer_store_byte v27, v0, s[0:3], 0 offen offset:178
; CHECK-NEXT:    buffer_store_byte v28, v0, s[0:3], 0 offen offset:177
; CHECK-NEXT:    buffer_store_byte v29, v0, s[0:3], 0 offen offset:176
; CHECK-NEXT:    buffer_store_byte v30, v0, s[0:3], 0 offen offset:175
; CHECK-NEXT:    buffer_store_byte v31, v0, s[0:3], 0 offen offset:174
; CHECK-NEXT:    buffer_store_byte v32, v0, s[0:3], 0 offen offset:173
; CHECK-NEXT:    buffer_store_byte v33, v0, s[0:3], 0 offen offset:172
; CHECK-NEXT:    buffer_store_byte v34, v0, s[0:3], 0 offen offset:171
; CHECK-NEXT:    buffer_store_byte v35, v0, s[0:3], 0 offen offset:170
; CHECK-NEXT:    buffer_store_byte v36, v0, s[0:3], 0 offen offset:169
; CHECK-NEXT:    buffer_store_byte v37, v0, s[0:3], 0 offen offset:168
; CHECK-NEXT:    buffer_store_byte v38, v0, s[0:3], 0 offen offset:167
; CHECK-NEXT:    buffer_store_byte v39, v0, s[0:3], 0 offen offset:166
; CHECK-NEXT:    buffer_store_byte v48, v0, s[0:3], 0 offen offset:165
; CHECK-NEXT:    buffer_store_byte v49, v0, s[0:3], 0 offen offset:164
; CHECK-NEXT:    buffer_store_byte v50, v0, s[0:3], 0 offen offset:163
; CHECK-NEXT:    buffer_store_byte v51, v0, s[0:3], 0 offen offset:162
; CHECK-NEXT:    buffer_store_byte v52, v0, s[0:3], 0 offen offset:161
; CHECK-NEXT:    buffer_store_byte v53, v0, s[0:3], 0 offen offset:160
; CHECK-NEXT:    buffer_store_byte v54, v0, s[0:3], 0 offen offset:159
; CHECK-NEXT:    buffer_store_byte v55, v0, s[0:3], 0 offen offset:158
; CHECK-NEXT:    buffer_store_byte v64, v0, s[0:3], 0 offen offset:157
; CHECK-NEXT:    buffer_store_byte v65, v0, s[0:3], 0 offen offset:156
; CHECK-NEXT:    buffer_store_byte v66, v0, s[0:3], 0 offen offset:155
; CHECK-NEXT:    buffer_store_byte v67, v0, s[0:3], 0 offen offset:154
; CHECK-NEXT:    buffer_store_byte v68, v0, s[0:3], 0 offen offset:153
; CHECK-NEXT:    buffer_store_byte v69, v0, s[0:3], 0 offen offset:152
; CHECK-NEXT:    buffer_store_byte v70, v0, s[0:3], 0 offen offset:151
; CHECK-NEXT:    buffer_store_byte v71, v0, s[0:3], 0 offen offset:150
; CHECK-NEXT:    buffer_store_byte v80, v0, s[0:3], 0 offen offset:149
; CHECK-NEXT:    buffer_store_byte v81, v0, s[0:3], 0 offen offset:148
; CHECK-NEXT:    buffer_store_byte v82, v0, s[0:3], 0 offen offset:147
; CHECK-NEXT:    buffer_store_byte v83, v0, s[0:3], 0 offen offset:146
; CHECK-NEXT:    buffer_store_byte v84, v0, s[0:3], 0 offen offset:145
; CHECK-NEXT:    buffer_store_byte v85, v0, s[0:3], 0 offen offset:144
; CHECK-NEXT:    buffer_store_byte v86, v0, s[0:3], 0 offen offset:143
; CHECK-NEXT:    buffer_store_byte v87, v0, s[0:3], 0 offen offset:142
; CHECK-NEXT:    buffer_store_byte v96, v0, s[0:3], 0 offen offset:141
; CHECK-NEXT:    buffer_store_byte v97, v0, s[0:3], 0 offen offset:140
; CHECK-NEXT:    buffer_store_byte v98, v0, s[0:3], 0 offen offset:139
; CHECK-NEXT:    buffer_store_byte v99, v0, s[0:3], 0 offen offset:138
; CHECK-NEXT:    buffer_store_byte v100, v0, s[0:3], 0 offen offset:137
; CHECK-NEXT:    buffer_store_byte v101, v0, s[0:3], 0 offen offset:136
; CHECK-NEXT:    buffer_store_byte v102, v0, s[0:3], 0 offen offset:135
; CHECK-NEXT:    buffer_store_byte v103, v0, s[0:3], 0 offen offset:134
; CHECK-NEXT:    buffer_store_byte v112, v0, s[0:3], 0 offen offset:133
; CHECK-NEXT:    buffer_store_byte v113, v0, s[0:3], 0 offen offset:132
; CHECK-NEXT:    buffer_store_byte v114, v0, s[0:3], 0 offen offset:131
; CHECK-NEXT:    buffer_store_byte v115, v0, s[0:3], 0 offen offset:130
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:708 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:129
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:704 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:128
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:700 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:127
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:696 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:126
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:692 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:125
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:688 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:124
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:684 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:123
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:680 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:122
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:676 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:121
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:672 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:120
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:668 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:119
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:664 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:118
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:660 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:117
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:656 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:116
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:652 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:115
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:648 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:114
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:644 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:113
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:640 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:112
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:636 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:111
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:632 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:110
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:628 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:109
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:624 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:108
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:620 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:107
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:616 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:106
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:612 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:105
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:608 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:104
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:604 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:103
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:600 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:102
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:596 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:101
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:592 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:100
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:588 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:99
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:584 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:98
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:580 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:97
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:576 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:96
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:572 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:95
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:568 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:94
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:564 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:93
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:560 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:92
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:556 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:91
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:552 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:90
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:548 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:89
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:544 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:88
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:540 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:87
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:536 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:86
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:532 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:85
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:528 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:84
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:524 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:83
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:520 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:82
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:516 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:81
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:512 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:80
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:508 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:79
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:504 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:78
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:500 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:77
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:496 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:76
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:492 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:75
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:488 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:74
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:484 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:73
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:480 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:72
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:476 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:71
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:472 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:70
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:468 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:69
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:464 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:68
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:460 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:67
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:456 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:66
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:452 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:65
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:448 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:64
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:444 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:63
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:440 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:62
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:436 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:61
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:432 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:60
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:428 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:59
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:424 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:58
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:420 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:57
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:416 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:56
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:412 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:55
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:408 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:54
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:404 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:53
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:400 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:52
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:396 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:51
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:392 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:50
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:388 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:49
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:384 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:48
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:380 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:47
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:376 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:46
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:372 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:45
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:368 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:44
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:364 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:43
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:360 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:42
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:356 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:41
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:352 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:40
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:348 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:39
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:344 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:38
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:340 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:37
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:336 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:36
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:332 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:35
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:328 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:34
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:324 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:33
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:320 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:32
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:316 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:31
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:312 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:30
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:308 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:29
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:304 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:28
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:300 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:27
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:296 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:26
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:292 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:25
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:288 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:24
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:284 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:23
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:280 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:22
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:276 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:21
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:272 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:20
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:268 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:19
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:264 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:18
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:260 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:17
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:256 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:16
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:252 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:15
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:248 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:14
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:244 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:13
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:240 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:12
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:236 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:11
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:232 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:10
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:228 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:9
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:224 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:8
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:220 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:7
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:216 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:6
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:212 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:5
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:208 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:4
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:204 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:3
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:200 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:2
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:196 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen offset:1
; CHECK-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:192 ; 4-byte Folded Reload
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    buffer_store_byte v2, v0, s[0:3], 0 offen
; CHECK-NEXT:    v_add_nc_u32_e32 v0, 0x100, v0
; CHECK-NEXT:    s_cbranch_vccnz .LBB0_1
; CHECK-NEXT:  ; %bb.2: ; %static-memcpy-post-expansion
; CHECK-NEXT:    s_clause 0x2f ; 192-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v127, off, s[0:3], s32
; CHECK-NEXT:    buffer_load_dword v126, off, s[0:3], s32 offset:4
; CHECK-NEXT:    buffer_load_dword v125, off, s[0:3], s32 offset:8
; CHECK-NEXT:    buffer_load_dword v124, off, s[0:3], s32 offset:12
; CHECK-NEXT:    buffer_load_dword v123, off, s[0:3], s32 offset:16
; CHECK-NEXT:    buffer_load_dword v122, off, s[0:3], s32 offset:20
; CHECK-NEXT:    buffer_load_dword v121, off, s[0:3], s32 offset:24
; CHECK-NEXT:    buffer_load_dword v120, off, s[0:3], s32 offset:28
; CHECK-NEXT:    buffer_load_dword v111, off, s[0:3], s32 offset:32
; CHECK-NEXT:    buffer_load_dword v110, off, s[0:3], s32 offset:36
; CHECK-NEXT:    buffer_load_dword v109, off, s[0:3], s32 offset:40
; CHECK-NEXT:    buffer_load_dword v108, off, s[0:3], s32 offset:44
; CHECK-NEXT:    buffer_load_dword v107, off, s[0:3], s32 offset:48
; CHECK-NEXT:    buffer_load_dword v106, off, s[0:3], s32 offset:52
; CHECK-NEXT:    buffer_load_dword v105, off, s[0:3], s32 offset:56
; CHECK-NEXT:    buffer_load_dword v104, off, s[0:3], s32 offset:60
; CHECK-NEXT:    buffer_load_dword v95, off, s[0:3], s32 offset:64
; CHECK-NEXT:    buffer_load_dword v94, off, s[0:3], s32 offset:68
; CHECK-NEXT:    buffer_load_dword v93, off, s[0:3], s32 offset:72
; CHECK-NEXT:    buffer_load_dword v92, off, s[0:3], s32 offset:76
; CHECK-NEXT:    buffer_load_dword v91, off, s[0:3], s32 offset:80
; CHECK-NEXT:    buffer_load_dword v90, off, s[0:3], s32 offset:84
; CHECK-NEXT:    buffer_load_dword v89, off, s[0:3], s32 offset:88
; CHECK-NEXT:    buffer_load_dword v88, off, s[0:3], s32 offset:92
; CHECK-NEXT:    buffer_load_dword v79, off, s[0:3], s32 offset:96
; CHECK-NEXT:    buffer_load_dword v78, off, s[0:3], s32 offset:100
; CHECK-NEXT:    buffer_load_dword v77, off, s[0:3], s32 offset:104
; CHECK-NEXT:    buffer_load_dword v76, off, s[0:3], s32 offset:108
; CHECK-NEXT:    buffer_load_dword v75, off, s[0:3], s32 offset:112
; CHECK-NEXT:    buffer_load_dword v74, off, s[0:3], s32 offset:116
; CHECK-NEXT:    buffer_load_dword v73, off, s[0:3], s32 offset:120
; CHECK-NEXT:    buffer_load_dword v72, off, s[0:3], s32 offset:124
; CHECK-NEXT:    buffer_load_dword v63, off, s[0:3], s32 offset:128
; CHECK-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:132
; CHECK-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:136
; CHECK-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:140
; CHECK-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:144
; CHECK-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:148
; CHECK-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:152
; CHECK-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:156
; CHECK-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:160
; CHECK-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:164
; CHECK-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:168
; CHECK-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:172
; CHECK-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:176
; CHECK-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:180
; CHECK-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:184
; CHECK-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:188
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  tail call void @llvm.memcpy.p5.p5.i64(ptr addrspace(5) noundef nonnull align 1 %dst, ptr addrspace(5) noundef nonnull align 1 %src, i64 2048, i1 false)
  ret void
}


declare void @llvm.memcpy.p5.p5.i64(ptr addrspace(5) noalias nocapture writeonly, ptr addrspace(5) noalias nocapture readonly, i64, i1 immarg) #2

attributes #1 = { nounwind }
attributes #2 = { nocallback nofree nounwind willreturn memory(argmem: readwrite) }
