; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5

; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1030 -mattr=-unaligned-access-mode %s -o - | FileCheck %s

; For checking that LowerMemIntrinsics lowers memcpy and memmove with large
; constant copy-sizes into loops with multiple load/store pairs.

define void @memset_p5_sz2048(ptr addrspace(5) %dst) #1 {
;
; CHECK-LABEL: memset_p5_sz2048:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v1, 0x41
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:  .LBB0_1: ; %static-memset-expansion-main-body
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_add_u32 s4, s4, 0x100
; CHECK-NEXT:    s_addc_u32 s5, s5, 0
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:255
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:254
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:253
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:252
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:251
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:250
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:249
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:248
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:247
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:246
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:245
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:244
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:243
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:242
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:241
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:240
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:239
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:238
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:237
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:236
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:235
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:234
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:233
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:232
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:231
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:230
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:229
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:228
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:227
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:226
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:225
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:224
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:223
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:222
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:221
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:220
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:219
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:218
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:217
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:216
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:215
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:214
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:213
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:212
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:211
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:210
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:209
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:208
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:207
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:206
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:205
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:204
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:203
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:202
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:201
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:200
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:199
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:198
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:197
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:196
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:195
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:194
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:193
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:192
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:191
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:190
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:189
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:188
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:187
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:186
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:185
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:184
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:183
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:182
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:181
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:180
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:179
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:178
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:177
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:176
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:175
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:174
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:173
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:172
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:171
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:170
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:169
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:168
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:167
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:166
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:165
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:164
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:163
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:162
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:161
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:160
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:159
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:158
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:157
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:156
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:155
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:154
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:153
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:152
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:151
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:150
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:149
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:148
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:147
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:146
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:145
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:144
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:143
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:142
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:141
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:140
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:139
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:138
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:137
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:136
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:135
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:134
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:133
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:132
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:131
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:130
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:129
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:128
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:127
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:126
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:125
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:124
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:123
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:122
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:121
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:120
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:119
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:118
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:117
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:116
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:115
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:114
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:113
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:112
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:111
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:110
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:109
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:108
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:107
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:106
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:105
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:104
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:103
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:102
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:101
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:100
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:99
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:98
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:97
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:96
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:95
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:94
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:93
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:92
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:91
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:90
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:89
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:88
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:87
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:86
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:85
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:84
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:83
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:82
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:81
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:80
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:79
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:78
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:77
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:76
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:75
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:74
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:73
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:72
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:71
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:70
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:69
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:68
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:67
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:66
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:65
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:64
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:63
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:62
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:61
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:60
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:59
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:58
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:57
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:56
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:55
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:54
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:53
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:52
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:51
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:50
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:49
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:48
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:47
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:46
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:45
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:44
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:43
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:42
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:41
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:40
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:39
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:38
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:37
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:36
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:35
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:34
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:33
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:32
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:31
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:30
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:29
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:28
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:27
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:26
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:25
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:24
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:23
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:22
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:21
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:20
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:19
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:18
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:17
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:16
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:15
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:14
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:13
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:12
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:11
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:10
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:9
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:8
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:7
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:6
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:5
; CHECK-NEXT:    v_cmp_gt_u64_e64 s6, 0x800, s[4:5]
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:4
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:3
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:2
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen offset:1
; CHECK-NEXT:    buffer_store_byte v1, v0, s[0:3], 0 offen
; CHECK-NEXT:    v_add_nc_u32_e32 v0, 0x100, v0
; CHECK-NEXT:    s_and_b32 vcc_lo, exec_lo, s6
; CHECK-NEXT:    s_cbranch_vccnz .LBB0_1
; CHECK-NEXT:  ; %bb.2: ; %static-memset-post-expansion
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  tail call void @llvm.memset.p5.i64(ptr addrspace(5) noundef nonnull %dst, i8 65, i64 2048, i1 false)
  ret void
}


declare void @llvm.memset.p5.i64(ptr addrspace(5) nocapture writeonly, i8, i64, i1 immarg) #3

attributes #1 = { nounwind }
attributes #3 = { nocallback nofree nounwind willreturn memory(argmem: write) }
