; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5

; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1030 -mattr=-unaligned-access-mode %s -o - | FileCheck %s

; For checking that LowerMemIntrinsics lowers memcpy and memmove with large
; constant copy-sizes into loops with multiple load/store pairs.

define void @memset_p1_sz2048(ptr addrspace(1) %dst) #1 {
;
; CHECK-LABEL: memset_p1_sz2048:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v4, 0x41414141
; CHECK-NEXT:    v_mov_b32_e32 v5, 0x41
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:  .LBB0_1: ; %static-memset-expansion-main-body
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    v_add_co_u32 v2, vcc_lo, v0, s4
; CHECK-NEXT:    s_add_u32 s4, s4, 0x100
; CHECK-NEXT:    v_add_co_ci_u32_e64 v3, null, s5, v1, vcc_lo
; CHECK-NEXT:    s_addc_u32 s5, s5, 0
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:152
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:156
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:148
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:144
; CHECK-NEXT:    v_cmp_gt_u64_e64 s6, 0x800, s[4:5]
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:250
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:251
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:249
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:255
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:254
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:253
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:252
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:248
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:247
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:246
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:245
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:244
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:243
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:242
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:241
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:240
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:168
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:172
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:164
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:160
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:234
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:235
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:233
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:239
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:238
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:237
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:236
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:232
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:231
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:230
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:229
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:228
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:227
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:226
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:225
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:224
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:120
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:124
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:116
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:112
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:218
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:219
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:217
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:223
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:222
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:221
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:220
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:216
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:215
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:214
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:213
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:212
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:211
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:210
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:209
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:208
; CHECK-NEXT:    s_and_b32 vcc_lo, exec_lo, s6
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:136
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:140
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:132
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:128
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:202
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:203
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:201
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:207
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:206
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:205
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:204
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:200
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:199
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:198
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:197
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:196
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:195
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:194
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:193
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:192
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:216
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:220
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:212
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:208
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:186
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:187
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:185
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:191
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:190
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:189
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:188
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:184
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:183
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:182
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:181
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:180
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:179
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:178
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:177
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:176
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:232
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:236
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:228
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:224
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:170
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:171
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:169
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:175
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:174
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:173
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:172
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:168
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:167
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:166
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:165
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:164
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:163
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:162
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:161
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:160
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:184
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:188
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:180
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:176
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:154
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:155
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:153
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:159
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:158
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:157
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:156
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:152
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:151
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:150
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:149
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:148
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:147
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:146
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:145
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:144
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:200
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:204
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:196
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:192
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:138
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:139
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:137
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:143
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:142
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:141
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:140
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:136
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:135
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:134
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:133
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:132
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:131
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:130
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:129
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:128
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:24
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:28
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:20
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:16
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:122
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:123
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:121
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:127
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:126
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:125
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:124
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:120
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:119
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:118
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:117
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:116
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:115
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:114
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:113
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:112
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:40
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:44
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:36
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:32
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:106
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:107
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:105
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:111
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:110
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:109
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:108
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:104
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:103
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:102
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:101
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:100
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:99
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:98
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:97
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:96
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:252
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:248
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:244
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:240
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:81
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:80
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:83
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:82
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:87
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:86
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:85
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:84
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:89
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:88
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:91
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:90
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:95
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:94
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:93
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:92
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:8
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:12
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:4
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:74
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:75
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:73
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:79
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:78
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:77
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:76
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:72
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:71
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:70
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:69
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:68
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:67
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:66
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:65
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:64
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:88
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:92
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:84
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:80
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:58
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:59
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:57
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:63
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:62
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:61
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:60
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:56
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:55
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:54
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:53
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:52
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:51
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:50
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:49
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:48
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:104
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:108
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:100
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:96
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:42
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:43
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:41
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:47
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:46
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:45
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:44
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:40
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:39
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:38
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:37
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:36
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:35
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:34
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:33
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:32
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:56
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:60
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:52
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:48
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:26
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:27
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:25
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:31
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:30
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:29
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:28
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:24
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:23
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:22
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:21
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:20
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:19
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:18
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:17
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:16
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:72
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:76
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:68
; CHECK-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:64
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:10
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:11
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:9
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:15
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:14
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:13
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:12
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:8
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:7
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:6
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:5
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:4
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:3
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:2
; CHECK-NEXT:    global_store_byte v[2:3], v5, off offset:1
; CHECK-NEXT:    global_store_byte v[2:3], v5, off
; CHECK-NEXT:    s_cbranch_vccnz .LBB0_1
; CHECK-NEXT:  ; %bb.2: ; %static-memset-post-expansion
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  tail call void @llvm.memset.p1.i64(ptr addrspace(1) noundef nonnull %dst, i8 65, i64 2048, i1 false)
  ret void
}


declare void @llvm.memset.p1.i64(ptr addrspace(1) nocapture writeonly, i8, i64, i1 immarg) #3

attributes #1 = { nounwind }
attributes #3 = { nocallback nofree nounwind willreturn memory(argmem: write) }
